authorizer/app.py, kube/template/init.sh
This PR adds the scope when we reissue the token from CILogon. It also removes the need for the `reissue_token` URL argument and a small fix for the jwks.json file
=> Add scope to initially reissued token

CHANGELOG.rst, src/jwt_authorizer/authnz.py, tests/authnz_test.py
A stray alogorithms parameter was added to the get_unverified_header
call instead of, as intended, jwt.decode.  Move it to the correct
call.
=> [DM-23646] Fix get_unverified_header call

CHANGELOG.rst, src/jwt_authorizer/tokens.py, tests/analyze_test.py
oauth2_proxy writes out a session date with nanoseconds, which
Python strptime doesn't know how to parse.  Patch around it with
a regex for now.
=> [DM-23646] Fix session date parsing

src/gafaelfawr/factory.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/util.py, tests/handlers/auth_test.py
- Don't redirect AJAX requests to external authentication providers
- Clean up and refactor some of the login code to make it easier to follow
- Hide the authentication provider implementation from the login route entirely
=> [DM-24302] Avoid authentication redirects for AJAX requests

CHANGELOG.rst, docs/arch/references.rst, docs/index.rst, docs/install.rst, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/tokens.py, src/gafaelfawr/handlers/util.py, tests/handlers/auth_test.py, tests/handlers/tokens_test.py, tests/setup.py, tests/support/tokens.py
Allow the authentication type for the challenge in WWW-Authenticate
to be configured via the auth_type parameter to the /auth route.
Some applications will want to present a Basic challenge instead.
Bring the challenges into compliance with RFC 6750 when returning
a Bearer challenge.  This specifically means no longer using a
free-form error and instead using the registered error types,
returning 400 instead of 401 in cases where the header could not
be parsed, and including a challenge with 400 and 403 responses.
Separate authenticated route handling for the tokens web interface
from the /auth handling.  The former only needs to know about the
API exported by ingress-nginx with the /auth handler, and mixing
that into the full parsing and return codes for the /auth handler
was confusing …
=> [DM-24635] Overhaul authentication challenges

docs/install.rst
The Helm chart now supports setting cilogin.login_params to pass
additional options to CILogon.
=> [DM-24662] Document cilogin.login_params Helm parameter

CHANGELOG.rst, README.rst, docs/conf.py, docs/configuration.rst, docs/dev/development.rst, docs/dev/release.rst, docs/index.rst, docs/logging.rst, setup.cfg, src/gafaelfawr/app.py, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/analyze.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/logout.py, src/gafaelfawr/handlers/tokens.py, src/gafaelfawr/handlers/util.py, src/gafaelfawr/handlers/well_known.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/session.py, src/gafaelfawr/token_store.py, src/gafaelfawr/verify.py, tests/handlers/analyze_test.py, tests/handlers/auth_test.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_test.py, tests/handlers/logout_test.py, tests/handlers/tokens_test.py
- Switch to the JSON log output format by default
- Add custom `remote` and `user_agent` attributes to every request
- Add additional custom attributes appropriate to various routes
- Ensure that all the routes log at least one message
- Standardize on separating the log message from the exception message
- Add tests for the logging
- Provide a nicer error message if someone goes to `/auth/analyze` without authentication
=> [DM-24685] Improve and document logging

CHANGELOG.rst, docs/arch/routes.rst, docs/conf.py, docs/install.rst, src/gafaelfawr/handlers/auth.py, tests/handlers/auth_test.py
- Add a route that can be used as a custom error handler for 403 errors
- Add Cache-Control headers to all errors returned by /auth
- Refactor the parsing of /auth route parameters
=> [DM-24753] Add support for suppressing caching of errors

CHANGELOG.rst, docs/arch/providers.rst, docs/install.rst, src/gafaelfawr/providers/github.py, tests/handlers/login_github_test.py, tests/handlers/logout_test.py, tests/setup.py, tests/support/http_session.py
Convert GitHub usernames and organizations to lowercase when forming identities and group membership for tokens. Refactor GitHub testing and team name handling.
=> [DM-24964] Lowercase GitHub usernames and organizations

CHANGELOG.rst, docs/logging.rst, src/gafaelfawr/x_forwarded.py, tests/x_forwarded_test.py
Work around a bug in version 1.39.1 of the Kubernetes NGINX ingress
by allowing multiple X-Forwarded-Proto headers in the incoming
request.
Add documentation for how to configure the NGINX ingress using the
Helm chart to get correct client IP addresses in logs.
=> [DM-24810] Support multiple X-Forwarded-Proto headers

.github/dependabot.yml
Enable Docker and GitHub Actions checks in addition to PIP (the
auto-detected default).
=> [DM-25183] Add dependabot configuration

.github/dependabot.yml
See if it makes a difference for frozen PIP requirements files to
enable updates for all dependencies, not just directly listed ones.
=> [DM-25183] Enable updates for all dependencies

docs/install.rst
Adjust the documentation for the official Helm chart to reflect
the new use of standard image subkeys, allowing Renovate to check
for out-of-date version references.
=> [DM-25183] Update Helm chart image documentation

.github/workflows/ci.yaml
Switches to the lsst-sqre org-based credentials for LSST the Docs.
=> Use org-based LTD credentials

.github/dependabot.yml, renovate.json
Delete configuration for Renovate, which we won't be using for
Python packages.  Change the schedule for Dependabot to weekly and
remove the PIP configuration, since that will be handled by
neophile.
=> [DM-25844] Update Dependabot and Renovate configuration

CHANGELOG.rst, docs/api.rst, docs/applications.rst, docs/arch/routes.rst, docs/configuration.rst, docs/install.rst, src/gafaelfawr/config.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/__init__.py, src/gafaelfawr/handlers/influxdb.py, src/gafaelfawr/issuer.py, src/gafaelfawr/settings.py, tests/handlers/influxdb_test.py, tests/settings/github.yaml.in, tests/support/app.py
InfluxDB expects a simple JWT authenticated with a shared key. Add a new
route to generate such a token based on a user's existing authentication.
=> [DM-26072] Add support for generating InfluxDB tokens

CHANGELOG.rst, docs/cli.rst, docs/conf.py, docs/index.rst, requirements/dev.in, requirements/dev.txt, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/analyze.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/decorators.py, src/gafaelfawr/handlers/logout.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/handlers/util.py, tests/handlers/analyze_test.py, tests/handlers/auth_logging_test.py, tests/handlers/auth_test.py, tests/handlers/influxdb_test.py, tests/handlers/oidc_test.py, tests/handlers/tokens_test.py, tests/handlers/userinfo_test.py, tests/support/app.py, tests/support/headers.py
- Add RFC-mandated headers to the OIDC token route
- Use the `authenticated_session` decorator for the `/auth/analyze` route
- Suppress subheadings for the changelog in the documentation
- Add command-line documentation
- Unify error handling and standardize on using exceptions with helper functions
- Simplify `RequestContext` creation
- Use shared code for validating logout redirects
- Simplify use of `Path` objects in tests
=> [DM-26072] Some cleanup refactoring after InfluxDB/Chronograf support

README.rst
Our versioning convention totally confuses badges.io's determination
of the Docker version.  Remove the badge to avoid advertising
incorrect information.
=> Remove Docker badge

CHANGELOG.rst, docs/applications.rst, docs/configuration.rst, docs/install.rst, src/gafaelfawr/config.py, src/gafaelfawr/handlers/influxdb.py, src/gafaelfawr/issuer.py, src/gafaelfawr/settings.py, tests/handlers/influxdb_test.py, tests/settings/influxdb-username.yaml.in
- Put the username in `username`, not `sub`, for InfluxDB tokens
- Add a new configuration parameter to force the username to a single value
=> [DM-26682] Fix various issues with InfluxDB tokens

CHANGELOG.rst, docs/applications.rst, docs/arch/references.rst, docs/arch/routes.rst, src/gafaelfawr/handlers/well_known.py, tests/handlers/well_known_test.py
Open Distro for Elasticsearch requires this to discover metadata
about the OpenID Connect implementation.  Implement it and add an
Open Distro for Elasticsearch example.
=> [DM-26602] Add /.well-known/openid-configuration route

src/gafaelfawr/cli.py
This isn't required since the entry points are defined in the
build system.
=> [DM-27700] Remove __main__ block in gafaelfawr.cli

src/gafaelfawr/handlers/analyze.py, src/gafaelfawr/providers/oidc.py, tests/handlers/analyze_test.py, tests/handlers/login_oidc_test.py, tests/support/setup.py, tests/support/tokens.py
Undo a poor choice I made during the FastAPI rewrite to change the
output format of /auth/analyze.  Nublado JupyterHub is using this
for now to retrieve token metadata, so convert the new token data
format to the old format we were previously generating when all
tokens were JWTs and use the same JSON structure.
This code (and route) can be dropped once JupyterHub can switch to
the new API and there's a new UI to show users their login metadata.
Also handle OpenID Connect providers that return invalid isMemberOf
structures, and ignore groups without GIDs (which are sometimes
returned by NCSA).
=> [DM-28666] Change /auth/analyze output to be backward compatible

src/gafaelfawr/verify.py
If the OpenID Connect provider's JWT token is missing expected
claims, log all the claims in the token in the error message to
aid in debugging.
=> [DM-28845] Log token claims when missing data

src/gafaelfawr/storage/kubernetes.py
The examples in the Python library use load_kube_config, but when
running inside a cluster with a mounted service token (the expected
use case), load_incluster_config is the correct initialization
function.
=> [DM-28898] Use load_incluster_config for Kubernetes

requirements/main.in, requirements/main.txt, src/gafaelfawr/constants.py, src/gafaelfawr/factory.py, src/gafaelfawr/services/token.py, src/gafaelfawr/token_cache.py, tests/support/setup.py, tests/token_cache_test.py
Cache internal and notebook tokens in a per-process in-memory cache
to reduce the database load.  The cached token is only returned for
the same parent token, only if the parent token expiration has not
changed, and (for internal tokens) the same service and requested
scopes.
=> [DM-29095] Add internal and notebook token caching

.pre-commit-config.yaml, CHANGELOG.rst, Dockerfile
We're exhausting the number of available connections on our Cloud
SQL instance because FastAPI is starting 40 workers.  This seems
excessive for a single Kubernetes pod; cap the worker count at 10
since we can scale horizontally with more pods.
=> [DM-28120] Cap FastAPI workers to 10

ui/package-lock.json, ui/package.json
Version 1.0.1 doesn't work with eslint for some reason.  Assume
this is an usptream bug and avoid that version.
=> Avoid react-alert-template-basic 1.0.1

CHANGELOG.rst, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/storage/token.py, tests/pages/tokens.py, tests/selenium/tokens_test.py, tests/support/selenium.py, tests/support/tokens.py, ui/package-lock.json, ui/src/components/timestamp.js, ui/src/components/tokenChangeTable.js, ui/src/components/tokenData.js, ui/src/components/tokenTable.js
In the UI, display expiration times of expired tokens as "expired"
instead of the delta from the current time.
Sort token lists by lats used (not yet populated), created, and
then alphabetically by token, since this will be more useful.
Reset the database before starting a Selenium test for more
reliable testing with persistent PostgreSQL.
Add an expired session token to the Selenium tests and add a test
for the new expires display behavior.
=> [DM-30706] Display expired tokens as expired

.dockerignore, .github/workflows/ci.yaml, Dockerfile
setuptools_scm was generating a development version for the
Gafaelfawr installed in the Docker image instead of a proper
version based on version tags.  Fix this by not excluding
checked-in directories via .dockerignore (since they show up as
local modifications), not using /app as a working directory, and
checking out the tags when building Docker images.
=> [DM-30907] Fix version in built Docker image

CHANGELOG.rst, docs/api.rst, src/gafaelfawr/models/link.py, src/gafaelfawr/providers/github.py, tests/handlers/api_history_test.py, tests/handlers/login_github_test.py, tests/support/headers.py, tests/support/setup.py
GitHub paginates the list of teams a user is a member of at 30
teams, and some people have considerably more teams than that.
Add support for pagination and retrieve the full list of teams.
Log all of the information we got from GitHub at debug logging
level.
=> [DM-30971] Support pagination of GitHub team results

CHANGELOG.rst, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/logout.py, src/gafaelfawr/models/state.py, src/gafaelfawr/providers/base.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/storage/token.py, tests/handlers/logout_test.py, tests/support/setup.py
During the first authentication from GitHub, the user chooses what
data to release to our application.  We have had persistent problems
where the user doesn't release the right data or they are not a
member of the correct organization when they first log on, and then
logging out and back in doesn't necessarily update what information
we can access via the GitHub access token.
On explicit logout, if the user logged on with GitHub, revoke the
OAuth authorization grant so that they're forced to go through the
permission screen again when they log in.  This should hopefully
avoid this issue at the cost of an extra screen when they return
after an explicit logout.
=> [DM-27980] Revoke GitHub OAuth grant on logout

CHANGELOG.rst, docs/applications.rst, src/gafaelfawr/handlers/auth.py, tests/handlers/auth_test.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_test.py
HTTP headers are not guaranteed to support character sets other
than ASCII, and Starlette forces them to ISO 8859-1.  This
interferes with correctly passing the user's full name to
protected services via HTTP headers.  Stop supporting sending
the full name in X-Auth-Request-Name and require the client get
the name from the user-info endpoint if needed.
Refactor the GitHub login test suite to remove code duplication.
=> [DM-31056] Do not send full name in HTTP headers

docs/dev/development.rst
The "inside Docker" instructions still require building the UI
first outside of Docker.  Adjust the documentation accordingly.
=> Building ui first also required for Docker dev

tests/handlers/analyze_test.py, tests/services/token_cache_test.py, tests/services/token_test.py
A few tests were performing database operations outside of a
transaction, which was blocking use of an async_scoped_session
for Gafaelfawr since the test would then not shut down properly.
Add explicit transactions for those database operations.
=> [DM-33662] Use more explicit database transactions in tests

tests/support/postgresql.conf, tox.ini
Bind-mount a PostgreSQL configuration into the container used for
testing to disable syncing and otherwise try to make PostgreSQL
run a little faster.  This only seems to save about 10%, but every
little bit helps.
=> [DM-33698] Optimize PostgreSQL for tests

CHANGELOG.rst, docs/api.rst, docs/conf.py, docs/configuration.rst, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/storage/ldap.py, src/gafaelfawr/verify.py, tests/handlers/login_oidc_test.py, tests/settings/oidc-ldap.yaml.in, tests/support/ldap.py, tests/verify_test.py
The OpenID Connect authentication provider has acquired several bits of LDAP code to retrieve user group information and the numeric UID. Both LDAP searches were done independently, the UID attribute had to be in the same base DN as the group information (some sites maintain group membership in a separate tree from user objects), and the integration with code to pull the same information from the upstream JWT tokens was awkward.
Refactor LDAP support into a separate LDAP storage layer, and maintain a cleaner separation between the OpenID Connect authentication provider and the token verification code. This is intended to achieve the following goals:
- Provide a generalized LDAP storage layer that could potentially be used with the GitHub provider if desired
- Reuse the same LDAP …
=> [DM-33718] Refactor LDAP handling

.github/workflows/ci.yaml, docs/api.rst, docs/conf.py, src/gafaelfawr/constants.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/services/admin.py, src/gafaelfawr/services/kubernetes.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/services/token.py, src/gafaelfawr/services/token_cache.py, src/gafaelfawr/storage/kubernetes.py, src/gafaelfawr/storage/token.py, src/gafaelfawr/verify.py, tests/conftest.py, tests/handlers/api_history_test.py, tests/support/settings.py, tox.ini
Try to make the tests run faster. The critical changes are to truncate tables instead of dropping them, and disable coverage by default, but the other changes seem to improve things minorly so keep them.
Also tweak the documentation generation a bit to match the changes in Safir.
=> [DM-33698] Speed up Gafaelfawr tests

CHANGELOG.rst, docs/dev/development.rst
- Remove reference to prettier (no longer used)
- Mention tox-docker and the Docker container creation
- Stop mentioning pytest and only recommend tox
- Document building the UI before running tests
- Document use of nvm
- Document the requirement for chromedriver
=> [DM-33812] Update development documentation

docs/configuration.rst, src/gafaelfawr/config.py, src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/storage/ldap.py, tests/handlers/login_oidc_test.py, tests/providers/oidc_verifier_test.py, tests/settings/oidc-ldap.yaml.in, tests/support/ldap.py
For integration with CILogon and COmanage, we'll need to take the
CILogon identifier and use LDAP to resolve it into a username from
COmanage.  Add support for this when using an OpenID Connect
provider.
Add support for simple binds to the LDAP server, required when using
the COmanage LDAP server.
=> [DM-34334] Support retrieving username from LDAP

CHANGELOG.rst, docs/configuration.rst, src/gafaelfawr/config.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/ldap.py, tests/handlers/login_oidc_test.py, tests/settings/oidc-ldap.yaml.in, tests/support/ldap.py
When using CILogon with COmanage, CILogon will pass an opaque
identifier in the sub claim that we need to look up in COmanage
LDAP to resolve to a user.  That was previously implemented, but
with a generic login error if the lookup failed.  However, a
lookup failure is expected for a new user, and rather than an
error, we want to direct that user to the self-service enrollment
flow so that they can create a pending COmanage record and be
added to the queue for approval.
Implement this via a new configuration parameter and a new
distinguished exception raised from the LDAP service layer if
all the queries succeeded but a user record was not found.
=> [DM-34592] Add enrollment URL support for OpenID Connect

src/gafaelfawr/main.py
Remove the workaround comment for a mypy issue and instead just
use importlib.metadata.version, since some version number should
always be set.
=> Rework getting the package version

CHANGELOG.rst, docs/configuration.rst, src/gafaelfawr/constants.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/logout.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/main.py, src/gafaelfawr/providers/base.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/base.py, src/gafaelfawr/storage/ldap.py, src/gafaelfawr/storage/oidc.py, src/gafaelfawr/storage/token.py, tests/conftest.py, tests/handlers/influxdb_test.py, tests/handlers/login_oidc_test.py, tests/handlers/oidc_test.py, tests/providers/oidc_verifier_test.py, tests/services/oidc_test.py, tests/services/userinfo_test.py, tests/support/ldap.py, tests/support/settings.py
- Tighten the regex for recognizing bot users
- Prefer `response_class` for redirects instead of constructing `RedirectResponse`
- Refactor common OIDC test code into a helper function
- Refactor how Gafaelfawr is configured in tests to use common functions
- Document `usernameClaim` and `uidClaim` configuration settings
- Use `Error` uniformly as a class name suffix for exceptions
- Better error reporting for LDAP or Firestore failures during login
=> [DM-34637] Minor refactoring and cleanup

docs/api.rst, docs/conf.py, src/gafaelfawr/cache.py, src/gafaelfawr/constants.py, src/gafaelfawr/dependencies/cache.py, src/gafaelfawr/dependencies/context.py, src/gafaelfawr/dependencies/ldap.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/main.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/firestore.py, src/gafaelfawr/services/ldap.py, src/gafaelfawr/services/token_cache.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/ldap.py, tests/conftest.py, tests/services/token_cache_test.py, tests/settings/oidc-ldap.yaml.in, tests/support/firestore.py, tests/support/ldap.py
The previous LDAP support in Gafaelfawr opened at least one new LDAP connection for each request that required an LDAP lookup, sometimes two. None of the data retrieved from LDAP was cached. It therefore leaned heavily on LDAP queries and LDAP connection setup being fast.
This PR hopefully provides more scaling by using an LDAP connection pool. This is unfortunately a bit awkward using the bonsai connection library, since bonsai does not handle connections that have timed out due to a firewall rule on the remote side and instead continues to return them from the pool. It also apparently busy-waits for replies from LDAP. Work around both (partially) by setting a timeout and by explicitly closing and reopening the connection when a timeout occurs.
The LDAP service is currently a pure …
=> [DM-34726] Use connection pool and cache for LDAP

.pre-commit-config.yaml, CHANGELOG.rst, docs/api.rst, docs/conf.py, docs/configuration.rst, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/cache.py, src/gafaelfawr/config.py, src/gafaelfawr/constants.py, src/gafaelfawr/factory.py, src/gafaelfawr/models/ldap.py, src/gafaelfawr/services/ldap.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/ldap.py, tests/handlers/login_oidc_test.py, tests/settings/oidc-ldap.yaml.in, tests/support/ldap.py, ui/package-lock.json
Add caches for LDAP groups, group names, and user information,
using the same per-user locking scheme as tokens.  These are
timed caches that invalidate after five minutes so that we pick
up changes to the underlying data while smoothing out load.
Also look up email address and full name from LDAP by default,
but allow this to be turned off with configuration.  Combine this
with UID lookups (if desired) so that we do a single LDAP query
for all of the user information.  Introduce a new model to hold
those results, since they're somewhat different than TokenUserInfo.
This results in significant backward-incompatible changes to the
LDAP configuration settings.  There are now three base DN settings:
one for groups, one for username lookup, and one for user record
lookup, and then which …
=> [DM-34726] Add caching of LDAP results

CHANGELOG.rst, src/gafaelfawr/cli.py, src/gafaelfawr/factory.py, src/gafaelfawr/services/firestore.py, tests/cli_test.py, tests/support/firestore.py
When converting an existing deployment to using Firestore for UID
and GID assignment, we will allocate new UIDs and will need to
change the ownership of everyone's home directories.  Add a new
command-line invocation that assumes every subdirectory of a
directory is a home directory, takes the username from the name of
the directory, allocates a UID, and sets ownership of the files
recursively with chown to that new UID.
=> [DM-34613] Add fix-home-ownership CLI invocation

CHANGELOG.rst, src/gafaelfawr/providers/oidc.py, tests/providers/oidc_verifier_test.py, tests/settings/oidc-subdomain.yaml.in
The implementation of OpenID Connect metadata discovery, used to
verify an upstream OpenID Connect ID token, did not correctly
follow the OpenID Connect Discovery protocol.  In particular, it
removed the last path component of the issuer URL before appending
the well-known address due to the default behavior of urljoin.
Stop using urljoin and correctly implement the protocol for
forming the URL.
=> [DM-35088] Fix finding OpenID Connect metadata

CHANGELOG.rst, src/gafaelfawr/cli.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/services/token.py, src/gafaelfawr/storage/base.py, src/gafaelfawr/storage/oidc.py, src/gafaelfawr/storage/token.py, tests/cli_test.py
Sometimes we'll do destructive upgrades where everyone's username
may change, and in that case we want to purge all Gafaelfawr data
since any remaining data will be meaningless.  Add a command-line
tool to do that.
Drop a workaround in CLI testing from when we were recreating
tables, which is no longer needed now that we're truncating tables
instead.
=> [DM-34613] Add command to delete all data

CHANGELOG.rst, src/gafaelfawr/constants.py, tests/services/token_test.py
Bring the valid username regex in sync with DMTN-255.
=> [DM-34613] Disallow all-numeric usernames

.github/workflows/ci.yaml, .gitignore, CHANGELOG.rst, docs/arch/internals.rst, docs/conf.py, docs/index.rst, examples/docker/gafaelfawr.yaml, requirements/dev.in, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/cli.py, src/gafaelfawr/dependencies/return_url.py, src/gafaelfawr/handlers/analyze.py, src/gafaelfawr/handlers/api.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/main.py, src/gafaelfawr/models/auth.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/models/token.py, tests/cli_test.py, tests/handlers/api_tokens_test.py, tests/pages/base.py, tox.ini
Use sphinxcontrib-redoc to generate REST API documentation at
api.html.  Move the internals Python API documentation to
arch/internals, since only developers will need to look at it.
In support of this, add a CLI command to spit out the OpenAPI
schema so that it can be used in the tox build.
I experimented with sphinxcontrib-openapi, but it appears to not
be maintained and has bitrotted, and I couldn't get it to work
with the OpenAPI schema generated by FastAPI.  Redoc does,
provided that I override the version of Redoc with the current
upstream release.
There is as yet no back link from the API documentation to the
rest of the documentation.
Now that the API documentation is of the REST API, move it up in
the documentation index.
Remove now-unnecessary documentation pins and fix an …
=> [DM-35238] Generate API documentation from OpenAPI spec

docs/arch/providers.rst
The GitHub group discussion talked about adding an isMemberOf claim,
which is no longer how Gafaelfawr works.  Remove that reference.
=> [DM-35644] Remove obsolete isMemberOf reference

src/gafaelfawr/services/token_cache.py
Use the same lock pattern for all caches including the token caches,
which means we check the token cache before locking, and then check
it again after locking.  Noticed while writing the implementation
tech note (DMTN-224).
=> [DM-30063] Check token cache before locking

CHANGELOG.md, src/gafaelfawr/services/token.py, src/gafaelfawr/storage/token.py, tests/handlers/api_tokens_test.py
When a user token was edited to change its scope, but not its
expiration time, its scopes were not updated in Redis.  Since Redis
is canonical for token scopes, this meant that the change appeared
to go through but had no actual effect.  Fixed by updating Redis if
either the scope or expiration of a user token is changed.
=> [DM-35842] Fix editing of token scopes

CHANGELOG.md, docs/configuration.rst, src/gafaelfawr/config.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/models/ldap.py, src/gafaelfawr/models/token.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/services/ldap.py, src/gafaelfawr/services/token.py, src/gafaelfawr/services/token_cache.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/ldap.py, tests/handlers/api_tokens_test.py, tests/handlers/auth_test.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_ldap_test.py, tests/settings/oidc-ldap-gid.yaml.in, tests/settings/oidc-ldap-uid.yaml.in, tests/support/tokens.py
- Support synthesizing user private groups, always for GitHub and optionally for LDAP setups
- Support a new GID field in the user authentication data and populate it from LDAP or the user private group
- Retrieve the group name corresponding to the primary GID from LDAP and add it to the user's group list if needed
=> [DM-35881] Implement user private groups and primary GID

src/gafaelfawr/services/userinfo.py, tests/handlers/login_oidc_ldap_test.py, tests/settings/oidc-ldap-firestore.yaml.in
In the Firestore case, a variable was reused incorrectly, causing
the primary GID of the user to be set to the GID of their last
group instead of the user private group.  Fix and add a test case.
=> [DM-35881] Fix primary GID assignment with Firestore

CHANGELOG.md, docs/configuration.rst, src/gafaelfawr/config.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/services/userinfo.py, tests/handlers/login_oidc_test.py, tests/settings/oidc-gid.yaml.in
Add new configuration options and support for obtaining the primary
GID from the OpenID Connect ID token rather than LDAP.  Previously,
unless LDAP was used, OpenID Connect authentications got no primary
GID.
=> [DM-36093] Add support for getting primary GID from OIDC token

CHANGELOG.md, docs/configuration.rst
The schedule for the CronJobs for audit and maintenance can be
configured in Helm.  Add that to the documentation.
=> [DM-35959] Add docs for Helm chart settings for CronJobs

CHANGELOG.md, docs/applications.rst, docs/configuration.rst, docs/dev/development.rst, src/gafaelfawr/config.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/userinfo.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_test.py, tests/providers/oidc_verifier_test.py, tests/settings/oidc-claims.yaml.in
This collection of changes supports getting group information from Keycloak in the CC-IN2P3 configuration.
- Allow the GID to be missing from the group membership details
- Allow overriding the OpenID Connect ID token claim that contains group membership
- Allow the claim to be a simple list of groups without dict structure
If the GID isn't provided, Gafaelfawr of course won't be able to provide it to protected applications, but it will still be available as user information and will be used for scope calculation.
Depends on https://github.com/lsst-sqre/nublado2/pull/166, which modifies nublado2 to not assume that all groups have GIDs. (nublado2 becuase it cares about POSIX groups has to skip any group without a GID.)
=> [DM-36093] Get group membership information more flexibly

src/gafaelfawr/logging.py, src/gafaelfawr/main.py
- Redirect uvicorn messages through structlog to add JSON formatting
- Parse the uvicorn access messages to populate a Google-style `httpRequest` log attribute
The motivation of this set of changes is to standardize on JSON as the log format for all Gafaelfawr logs, allowing easier log queries and exploration in systems like Google Log Explorer that automatically understand JSON structure and allow individual fields to be used in queries and filters. As a secondary benefit, this will also avoid misclassification by Google of pure text logs as errors when they're intended to have a lower severity, by lifting the actual Python log severity into JSON in the field where Google expects it.
=> [DM-35879] Log uvicorn messages in JSON

CHANGELOG.md, docs/applications.rst, src/gafaelfawr/auth.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/services/token.py, src/gafaelfawr/services/token_cache.py, tests/handlers/auth_test.py
Add a parameter to the /auth route to specify a required minimum lifetime.  This is measured against the lifetime of any delegated token that we would pass on to the service, such as a notebook token for the Notebook Aspect (the motivating application), but it can be used as a check against the user's session token lifetime if desired.
This is a bit more complicated than immediately apparent since we have to do some careful logic to extrapolate from the lifetime of the user's authentication token to the lifetime of a delegated token, and we have to support invalidating the cache and generating a new delegated token even if more than half of its lifetime is still remaining.
=> DM-29094: Support a required minimum lifetime

src/gafaelfawr/cli.py, tests/cli_test.py
Slack doesn't recognize lists in mrkdwn, so we have to simulate them with the Unicode bullet character.
=> DM-36247: Fix bullet for audit alerts

CHANGELOG.md, src/gafaelfawr/constants.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/services/token.py, src/gafaelfawr/services/token_cache.py, tests/handlers/auth_test.py
If and only if a delegated token is requested, force the minimum lifetime to be at least MINIMUM_LIFETIME (five minutes).  This will hopefully fix a problem that caused an exception in production due to an invalid Redis key expiration time, presumably because someone attempted to authenticate with a token that was about to expire, resulting in a delegated token with a lifetime of 0 seconds.
=> DM-36438: Set minimum expiration for delegated tokens

.github/workflows/ci.yaml
This is failing because I updated a link in CHANGELOG.md to point to the new structure, but the new structure hasn't been deployed on the live site yet because the linkcheck is failing.
=> DM-36366: Temporarily stop running linkcheck

requirements/dev.in, requirements/dev.txt
pytest-sugar needs py but pytest no longer depends on it.
=> Fix pytest-sugar dependencies

tests/crds/service-token.yaml
I had deleted the schema for the GafaelfawrServiceToken status section, since Kopf also uses it and the format had changed. However, the create and periodic portions of the status do have a reliable schema.  Only the Kopf stuff may change independently and is handled by the x-kubernetes-preserve-unknown-fields annotation.
Also update additionalPrinterColumns to not refer to status columns that had been removed.
=> DM-28493: Add a schema for GafaelfawrServiceToken status

CHANGELOG.md
The change log link to disabling error caching was invalidated by some reorganization of the documentation as part of adding support for GafaelfawrIngress.  Fix the link.
=> DM-28493: Fix change log link

CHANGELOG.md, src/gafaelfawr/cache.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/services/ldap.py, src/gafaelfawr/services/userinfo.py, tests/handlers/login_oidc_ldap_test.py
If we reject the login because the user is not a member of any valid groups, invalidate the LDAP cache so that the next attempt will check LDAP again.  The user is probably going to try to fix the problem right away, and we don't want to make them wait for the LDAP cache to time out before they can see if their fix worked.
=> DM-37192: Invalidate the LDAP cache if login was rejected

.github/workflows/ci.yaml, CHANGELOG.md, docs/user-guide/gafaelfawringress.rst, docs/user-guide/ingress-overview.rst, docs/user-guide/manual-ingress.rst, src/gafaelfawr/auth.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/auth_test.py
Reflect the Authorization and Cookie headers from the request back in the response from the /auth route with Gafaelfawr tokens and cookies filtered out.  Lift those headers into the request to the protected service via NGINX Ingress annotation in the Ingress resources created from GafaelfawrIngress, and document how to do this for manually-configured ingresses.
This prevents leaking the user's original credentials to protected services, which could reuse them to impersonate the user beyond the scope of their delegated tokens.
=> DM-37291: Add Authorization and Cookie header filtering

CHANGELOG.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/manual-ingress.rst, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/auth_test.py
Add new config.delegate.useAuthorization GafaelfawrIngress setting and use_authorization query parameter to the /auth route that also puts a copy of any delegated token into the Authorization header as a bearer token.  The CADC TAP service requires the token be passed that way to work well with their authentication layer, and this removes the need for a custom NGINX configuration snippet.
=> DM-37291: Support passing delegated token in Authorization

CHANGELOG.md, src/gafaelfawr/operator/ingress.py, src/gafaelfawr/operator/tokens.py, tests/operator/ingress_test.py
Add an on-resume hook to the Kopf handling of ingress resources so that we update ingresses for changes in the Gafaelfawr source code. This seems sufficient for ingresses and the full periodic timer checks don't seem necessary, since there's nothing intrinsic to the ingress (unlike the secret generated from a GafaelfawrServiceToken) that should change outside of Gafaelfawr source code changes.
=> DM-37291: Check Ingress resources on operator resume

.github/workflows/ci.yaml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/manual-ingress.rst
- Document how to request a basic auth challenge
- Use separate tox caches for docs and test to reduce download and upload sizes
=> DM-37291: Document authType, change tox cache

CHANGELOG.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/manual-ingress.rst, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/auth_test.py, tests/models/kubernetes_test.py, tests/operator/ingress_test.py
Allow a GafaelfawrIngress to specify that it is anonymous.  In this case, most of the configuration is not allowed, but Gafaelfawr is still configured as the auth-uri so that it can strip tokens and cookies from the Authorization and Cookie headers.  Add a new route, /auth/anonymous, that does only this stripping.
Also diagnose a GafaelfawrIngress that requests a basic authentication challenge but also wants an auth redirect, since those are mutually incompatible.
=> DM-37291: Add support for anonymous ingresses

CHANGELOG.md, docs/user-guide/ingress-overview.rst, src/gafaelfawr/auth.py, tests/handlers/auth_test.py
Rather than requiring the user use an x-oath-basic placeholder in the other field, take advantage of the fact that our tokens have a well-known format and accept tokens in either the username or the password field.  If both fields are tokens, they must match.
The original design was based on an earlier iteration of how GitHub handled Basic Auth, but GitHub now supports putting the token in either field without any special marking, which seems more convenient and easier to explain.
=> DM-37470: Accept tokens in either field of Basic Auth

CHANGELOG.md, examples/docker/gafaelfawr.yaml, examples/gafaelfawr-dev.yaml, examples/gafaelfawr-github.yaml, examples/gafaelfawr-oidc.yaml, src/gafaelfawr/config.py, tests/data/config/bad-admin.yaml, tests/data/config/bad-loglevel.yaml, tests/data/config/bad-scope.yaml, tests/data/config/bad-token.yaml.in, tests/data/config/both-providers.yaml, tests/data/config/github-oidc-server.yaml.in, tests/data/config/github.yaml.in, tests/data/config/missing-scope.yaml, tests/data/config/no-provider.yaml, tests/data/config/oidc-claims.yaml.in, tests/data/config/oidc-enrollment.yaml.in, tests/data/config/oidc-firestore.yaml.in, tests/data/config/oidc-gid.yaml.in, tests/data/config/oidc-ldap-firestore.yaml.in, tests/data/config/oidc-ldap-gid.yaml.in, tests/data/config/oidc-ldap-groups.yaml.in, tests/data/config/oidc-ldap-uid.yaml.in, tests/data/config/oidc-ldap.yaml.in, tests/data/config/oidc-no-kids.yaml.in, tests/data/config/oidc-subdomain.yaml.in, tests/data/config/oidc.yaml.in, tests/data/config/selenium.yaml.in
To avoid the divergence between the on-disk configuration file and the Helm values file in Phalanx, enable camel-case support for the parsing of the disk configuration file.  Update all examples and test configuration files accordingly.
Stop using BaseSettings because we don't want to support environment variables or .env files, and those are the only things BaseSettings adds over BaseModel.
Enable slots for the frozen configuration for minor performance and memory benefits.
=> DM-37833: Support camel-case in configuration

src/gafaelfawr/config.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/userinfo.py, tests/data/config/github-quota.yaml.in, tests/handlers/api_tokens_test.py, tests/handlers/quota_test.py
Support configuring default and per-group quotas in the Gafaelfawr settings, calculate the user's total quotas when user information is requested, and include that in the token user information model. Also reorder settings in gafaelfawr.config to match between settings and the frozen configuration and hopefully be a bit more readable.
Includes a bit of reformatting in the test suite that I noticed while updating the tests for quota handling.
=> DM-37833: Add basic quota support

CHANGELOG.md, docs/dev/requirements.rst, src/gafaelfawr/auth.py, src/gafaelfawr/handlers/login.py, tests/handlers/auth_test.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_test.py, tests/support/headers.py
Some browsers appear to cache the 307 enrollment flow redirect and send the user back into the enrollment flow when they try to log in after they have enrolled.
Uniformly use Cache-Control: no-cache, no-store when disabling caching. (no-store should make no-cache unnecessary, but I believe it is a later keyword that earlier browsers may not support.) Previously, Gafaelfawr also added must-revalidate, but this doesn't appear to be necessary with modern browsers and was likely only meaningful combined with max-age=0 (which Gafaelfawr didn't set).
=> DM-38170: Disable caching of enrollment redirects

CHANGELOG.md, src/gafaelfawr/constants.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/operator/startup.py
Set a timeout on Kubernetes watches in Kopf rather than using an unlimited watch. https://github.com/nolar/kopf/issues/585 says that watches without an expiration sometimes go silent and stop receiving events, which is consistent with some problems we've seen.
Mark Kubernetes object parsing failures as permanent so that Kopf won't retry with the same version of the object. Mark Kubernetes API failures as temporary so that Kopf will use its normal delay.
=> DM-38376: Improve Kopf configuration and error handling

src/gafaelfawr/config.py
When some required scopes are missing from the knownScopes configuration, the error reporting failed because it referenced an invalid variable.
=> DM-38414: Fix error reporting when knownScopes incomplete

pyproject.toml, src/gafaelfawr/exceptions.py
- Fix the documented return type of `SlackWebException.from_exception`
- Add `project.authors` and a change log and issue tracker URL to the project metadata
=> DM-38414: Minor documentation fixes

.github/workflows/ci.yaml, .github/workflows/linkcheck.yaml
- Run linkchecks separately so that they can be advisory and not block merges.
- Run a linkcheck weekly.
- Update the minikube and Kubernetes versions.
- Enable support for merge queues, which required tweaking some workflow conditionals.
=> DM-38414: Update GitHub Actions configuration

changelog.d/20230413_120335_rra_DM_38414a.md, changelog.d/20230413_123131_rra_DM_38414a.md, docs/user-guide/helm.rst, examples/docker/gafaelfawr.yaml, examples/gafaelfawr-dev.yaml, src/gafaelfawr/config.py, src/gafaelfawr/handlers/api.py, src/gafaelfawr/main.py, tests/config_test.py, tests/data/config/bad-log-level.yaml, tests/data/config/bad-token.yaml.in, tests/data/config/oidc-forgerock.yaml.in, tests/data/config/oidc-ldap-gid.yaml.in, tests/data/config/oidc-ldap-groups.yaml.in, tests/data/config/oidc-ldap-uid.yaml.in, tests/data/config/oidc-ldap.yaml.in, tests/support/config.py
- Use `logLevel` as the configuration option and `log_level` as the internal attribute, not `loglevel`, to match other packages
- Stop adding timestamps to log messages now that Argo CD supports showing timestamps
- Use full paths in all of the handlers to make the code clearer
- Move lifecycle and exception handlers into `create_app` since they're private implementation details and it makes the code more succinct
=> DM-38414: Tweak the application setup

changelog.d/20230418_091146_rra_DM_38747.md, docs/user-guide/helm.rst, docs/user-guide/secrets.rst, scripts/install-base-packages.sh, scripts/start.sh, src/gafaelfawr/config.py, src/gafaelfawr/factory.py
Install the required libraries and the k5start program in the container and, if a keytab and krb5.conf file are present in the container, run the application under k5start. (This will be handled by the Helm chart for invocations other than the default uvicorn one.) If ldap.useKerberos is set in the configuration and there is no userDn set, use GSSAPI as the authentication method.
Add documentation for the secret and Helm configuration. Reorganize the LDAP configuration documentation a bit to use subheadings.
=> DM-38747: Support Kerberos GSSAPI binds to LDAP

src/gafaelfawr/exceptions.py, src/gafaelfawr/main.py
Convert NotConfiguredError and PermissionDeniedError to inherit from InputValidationError, since they have the same semantics. This allows eliminating the extra exception handlers.
=> DM-38414: Use InputValidationError for more exceptions

src/gafaelfawr/exceptions.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py, tests/handlers/login_oidc_test.py
There were still some places where the GitHub provider was raising raw HTTPX exceptions, and where it wasn't, it and the OIDC provider were using ProviderWebError. Use GitHubWebError or OIDCWebError uniformly.
=> DM-38414: Use separate HTTPX exceptions for providers

changelog.d/20230414_125547_rra_DM_38414.md, src/gafaelfawr/factory.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/storage/oidc.py, src/gafaelfawr/storage/token.py, tests/data/config/github-oidc-server.yaml.in, tests/services/oidc_test.py, tests/services/token_cache_test.py, tests/services/token_test.py
When we were unable to deserialize data stored in Redis, the OpenID Connect provider reported an error saying that the user's code was invalid (with a more detailed error message), and the token code treated the token as nonexistent. A more detailed error message was logged, but that would be easy to miss.
Keep the same public-facing behavior, but report these errors to Slack since they possibly indicate infrastructure data corruption. Do not do this when the problem is that the secret portion of the token is invalid; instead, continue to treat that as an invalid code or token and log an error but not to Slack.
=> DM-38414: Report Redis deserialization errors to Slack

changelog.d/20230414_141517_rra_DM_38414.md, src/gafaelfawr/constants.py, src/gafaelfawr/factory.py
Enable TCP keepalive on the Redis connection since sometimes environments have weird firewall behavior. Enable retries on failed Redis connections, starting at 0.1 seconds and exponentially increasing to 1 second with five retries.
=> DM-38414: Enable Redis keepalive and retries

changelog.d/20230414_130832_rra_DM_38414.md, docs/dev/configuration.rst, docs/dev/development.rst
tox v4 now wants a subcommand before flags, and tox -e run doesn't work properly any more because of it. Change the documentation to reflect the new syntax.
=> DM-38414: Document the new tox command line

docs/_templates/autosummary_core/exception.rst, docs/dev/internals.rst, docs/documenteer.toml, docs/index.rst, pyproject.toml, src/gafaelfawr/cache.py, src/gafaelfawr/middleware/state.py, src/gafaelfawr/models/admin.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/models/token.py, src/gafaelfawr/storage/kubernetes.py, tox.ini
- Remove the sidebars on some API documentation pages since they don't seem to add much value
- Remove now-unneeded nitpick exclusions
- Include TypeVar in the documentation but drop docstrings for nested Pydantic Config classes
- Add descriptions to more Pydantic model fields
- Delete automodapi files on doc generation to avoid errors from out-of-date code
- Support method and attribute documentation for exceptions
- Add missing API documentation for the ingress operator
=> DM-38414: Improve API documentation

tox.ini
tox v4 appears to prefer allowlist_externals instead of whitelist_externals.
=> DM-38414: Use allowlist_externals

.github/workflows/ci.yaml
Disable GitHub Actions CI on push to branches used by the merge queue.
=> DM-38414: Do not build on push with merge queues

changelog.d/20230515_120829_rra_DM_39186.md, src/gafaelfawr/constants.py, src/gafaelfawr/factory.py, tests/support/selenium.py
Since adding more connection retry configuration, we have been seeing periodic "Connection closed by server" errors in all environments. One hypothesis is that setting socket_keepalive is keeping the connection open longer than the Redis server permits, and it's changing the error in a way that's causing this problem. Try dropping that configuration.
Stop setting an explicit list of exceptions on which to retry, since the default seems to be fine.
=> DM-39186: Redo Redis connection configuration

CHANGELOG.md, changelog.d/20230515_120829_rra_DM_39186.md, changelog.d/20230515_152805_rra_DM_39186.md, requirements/main.in, requirements/main.txt
This is no longer required for static web service in FastAPI.
=> DM-39186: Drop aiofiles dependency

src/gafaelfawr/templates.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_test.py
Override the loader for the Starlette Jinja environment to use PackageLoader instead of FileSystemLoader. Our templates are included in the package, so this is technically more correct.
=> DM-39486: Use PackageLoader to load templates

changelog.d/20230601_142330_rra_DM_39486.md, src/gafaelfawr/storage/ldap.py
We know we have lots of internal COmanage internal groups that start with CO: that aren't worth warning about. Turn warnings about groups with that name pattern into debug messages.
=> DM-39486: Suppress warnings about CO: groups

changelog.d/20230605_084645_rra_DM_39519.md, pyproject.toml, src/gafaelfawr/cli.py
When switching to the Ruff linter, output from the CLI changed to use sys.stdout.write instead of print. That caused the newline after generated session secrets and tokens to accidentally be dropped. Restore it.
=> DM-39519: Add newline back to Gafaelfawr CI output

.github/workflows/ci.yaml, .github/workflows/dependencies.yaml, .github/workflows/periodic.yaml, tox.ini
Add neophile-check and neophile-update tox targets, and use the run-tox GitHub Action to run them instead of manually setting up Python and installing neophile manually.
=> DM-39989: Use tox to run neophile

.github/workflows/ci.yaml, .github/workflows/dependencies.yaml, .github/workflows/periodic-ci.yaml
The GitHub Action to set up minikube that the test suite was using is apparently no longer supported, so switch to the one that's recommended by the minikube documentation and is now used in Phalanx.
Remove some unnecessary name settings for action steps, and rename the periodic workflow file to periodic-ci, matching the current templates.
=> DM-40041: Switch minikube setup actions

.github/workflows/periodic-ci.yaml
Running every tox CI environment in serial can take a while, so increase the timeout to 20 minutes from 10 minutes.
=> Increase the timeout for periodic CI

pyproject.toml
Add a few more exclusions that were required for neophile and seem like a good idea in general.
=> DM-40567: Synchronize Ruff configuration with neophile

changelog.d/20230830_145513_rra_DM_40567b.md, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/factory.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingress-error-scope.yaml, tests/operator/ingress_test.py
Check the validity of scopes in a GafaelfawrIngress Kubernetes object and set an error status rather than creating an Ingress that will always fail.
=> DM-40567: Diagnose invalid GafaelfawrIngress scopes

requirements/dev.txt, requirements/main.txt, tests/handlers/oidc_test.py
Fix a test that failed because the redirect URL parameter in the redirect returned by OpenID Connect login now encodes the slashes, whereas before it doesn't. Some change in dependencies must have done that.
=> Update Python dependencies

changelog.d/20231002_161626_rra_DM_23878.md, docs/documenteer.toml, docs/user-guide/helm.rst, src/gafaelfawr/config.py, src/gafaelfawr/providers/oidc.py, src/gafaelfawr/storage/ldap.py, tests/data/config/oidc-ldap-memberdn.yaml.in, tests/handlers/login_oidc_ldap_test.py, tests/handlers/login_oidc_test.py
Most LDAP servers put the full user DN in the membership attribute of the group tree. Add a boolean configuration option to specify this search behavior, constructing the DNs using the user base DN and search attribute. This requires that user LDAP information also be enabled, but I'm hoping to drop support for getting only groups from LDAP and not also users, so this isn't a major drawback and it allows simplification of the configuration and avoids supporting too many degrees of freedom.
Log more debugging information about upstream OIDC tokens.
Restructure the validation of the LDAP settings object to take more advantage of Pydantic v2 validators by using model validators instead of field validators where more appropriate. Remove all of the defaults from the frozen config, since that …
=> DM-23878: Allow the LDAP group search to be configured

changelog.d/20231006_082903_rra_DM_41075.md, changelog.d/20231006_083302_rra_DM_41075.md, scripts/install-base-packages.sh, src/gafaelfawr/providers/oidc.py
Rather than just raising exceptions during various OIDC provider parse errors, also log those exceptions. Include the body of the response from the token URL if we cannot parse it as valid JSON, since hopefully the chances that it contains secure information are low in that case.
=> DM-41075: Log OIDC exceptions properly

changelog.d/20231006_141539_rra_DM_41090.md, docs/user-guide/helm.rst
Document the deadline and cleanup time for maintenance jobs and the requests and limits that are now set for all pods.
=> DM-41090: Document new Helm chart settings

changelog.d/20231027_101349_rra_DM_41424.md, src/gafaelfawr/constants.py, src/gafaelfawr/factory.py
The retry specification for the Redis connection pool was passed into the Redis constructor rather than the connection pool constructor, which appears to mean it was unused. Pass it into the connection pool constructor instead, add a socket timeout, and enable socket keepalive. This hopefully will fix a problem we saw where Gafaelfawr never recovered from the Redis server being restarted during Kubernetes maintenance.
=> DM-41424: Improve Redis pool configuration

changelog.d/20231027_125137_rra_DM_41424.md, src/gafaelfawr/constants.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/output/ingresses.yaml
Gafaelfawr was picking and choosing which headers to mask in the Ingress created from a GafaelfawrIngress based on which headers Gafaelfawr would set, but from a security standpoint it's better to mask all of the headers Gafaelfawr may set to ensure that they can never be provided by a hostile client.
=> DM-41424: Always mask all Gafaelfawr response headers

pyproject.toml, src/gafaelfawr/auth.py, src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/services/kubernetes.py, src/gafaelfawr/services/token.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/ldap.py
Address all of the Ruff-diagnosed excess complexity by breaking up methods and functions, except for the transformation of `Settings` to `Config`. That hasn't yet been addressed.
=> DM-41424: Refactor to reduce complexity

.pre-commit-config.yaml, Makefile, changelog.d/20231204_142753_rra_DM_41998.md, changelog.d/20231204_144736_rra_DM_41998.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/manual-ingress.rst, pyproject.toml, requirements/dev.in, requirements/dev.txt, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/models/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/auth_test.py
Allow ingresses to be restricted to a specific named user by setting the user attribute in the config section of a GafaelfawrIngress, or the corresponding user query parameter to the /auth route. Any other user will receive a 403 error. The scope requirements must also still be met.
=> DM-41998: Add support for per-user ingresses

.github/workflows/ci.yaml
Update actions/upload-artifact and actions/download-artifact together in the same PR, since the older versions and newer versions apparently do not interoperate.
=> Update artifact actions

changelog.d/20240110_125829_rra_DM_42384.md, docs/user-guide/openid-connect.rst, examples/docker/gafaelfawr.yaml, examples/gafaelfawr-dev.yaml, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/services/token.py, tests/cli_test.py, tests/handlers/oidc_test.py, tests/services/oidc_test.py, tests/services/token_test.py
Stop exposing all known claims by default in the issued ID token and instead honor scopes requested by the client. Currently, the supported scopes include the profile and email scopes defined by OpenID Connect (insofar as Gafaelfawr has the data).
Set the aud claim on ID tokens to the client ID rather than a fixed audience value that matches the Gafaelfawr issuer, bringing the implementation in line with the intent of the specification.
Tie the expiration time of OpenID Connect ID tokens to the expiration of the underlying Gafaelfawr token used as an authentication basis.
Require the oidcServer.issuer configuration setting use the https scheme, since the protocol requires that. Include the scope that was used for ID token issuance in the response from the token endpoint, since the spec …
=> DM-42384: Fix protocol issues in OpenID Connect server

changelog.d/20240117_152943_rra_DM_42384.md, docs/user-guide/helm.rst, docs/user-guide/openid-connect.rst, src/gafaelfawr/config.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/services/oidc.py, tests/data/config/github-oidc-server.yaml.in, tests/handlers/oidc_test.py
Add a rubin scope for the OpenID Connect server and a data_rights claim that it enables. This claim will contain a space-separated list of data releases to which the user has access rights, and is intended for use by IDACs (see DMTN-253).
Add a new config.oidcServer.dataRightsMapping configuration option that tells Gafaelfawr how to determine those data rights from the user's group memberships.
=> DM-42384: Add support for data rights information

changelog.d/20240123_163221_rra_DM_42384.md, docs/user-guide/openid-connect.rst, src/gafaelfawr/config.py, src/gafaelfawr/dependencies/return_url.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/services/oidc.py, tests/cli_test.py, tests/handlers/oidc_test.py, tests/services/oidc_test.py, tests/support/config.py
In order to allow OpenID Connect clients to be at any domain, not just one that matches Gafaelfawr's domain, require OpenID Connect clients to pre-register their return URL. This changes the format of the oidc-server-secrets secret, since this is now a mandatory parameter. Verify that it matches the registered client information in the OIDC routes.
=> DM-42384: Add OpenID Connect return URL registration

.pre-commit-config.yaml, Dockerfile, alembic.ini, alembic/README, alembic/env.py, alembic/gafaelfawr.yaml, alembic/script.py.mako, alembic/versions/20240209_2310_2feb306dd1ee_add_oidc_token_type.py, changelog.d/20240209_160742_rra_DM_42384.md, docs/_rst_epilog.rst, docs/dev/development.rst, examples/secrets/oidc-clients.json, pyproject.toml, requirements/dev.in, requirements/dev.txt, requirements/main.in, requirements/main.txt, scripts/start.sh, src/gafaelfawr/cli.py, src/gafaelfawr/config.py, src/gafaelfawr/models/token.py, tests/config_test.py, tox.ini
Add a new oidc token type as an initial migration, which is not yet used but will be used in a subsequent change.
Use an async engine for Alembic, since that avoids needing to also install psycopg2 alongside asyncpg only for Alembic to use it. Since Alembic only sort-of supports async via asyncio.run, this requires moving the body of gafaelfawr init into a separate coroutine and running that with asyncio.run so that Alembic can be run outside of the running async loop.
The Alembic environment is a bit complicated at the moment and duplicates a bit of Safir code. A lot of this can be lifted into Safir in the future.
Fix a few problems with secret loading uncovered by loading the example configuration: the example OIDC client secrets were missing the new return_uri field, and newlines …
=> DM-42384: Add support for database migrations with Alembic

changelog.d/20240213_170118_rra_DM_42384a.md, docs/dev/glossary.rst, src/gafaelfawr/auth.py, src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/services/oidc.py, src/gafaelfawr/services/token.py, tests/cli_test.py, tests/handlers/oidc_test.py, tests/services/oidc_test.py
Instead of setting the access token for OpenID Connect authentications to the same as the ID token, issue a new Gafaelfawr token of the oidc type with no scopes. Change the userinfo endpoint to expect that token instead.
This means that the access token will be automatically revoked if the authentication token used to authenticate the OpenID Connect login is revoked.
=> DM-42384: Issue oidc tokens for OIDC access tokens

Dockerfile, changelog.d/20240214_133634_rra_DM_42384.md, src/gafaelfawr/cli.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/main.py, tests/conftest.py, tests/support/selenium.py
Unless it is explicitly disabled (such as by the test suite), check the schema with Alembic during startup to see if it's current and refuse to start if it isn't. Test this by keeping schema validation enabled during Selenium testing, which runs via uvicorn and thus simulates how Gafaelfawr is run in production.
This required changing the Selenium fixtures to not be async, since Alembic doesn't like async for some things. They turned out to have no reason to be async, so this was painless.
At present, this only handles web application startup, not the Kubernetes operator or the audit or maintenance cron jobs.
=> DM-42384: Verify the database schema on startup

alembic/env.py, alembic/versions/20240209_2310_2feb306dd1ee_add_oidc_token_type.py, changelog.d/20240214_185441_rra_DM_42384.md, pyproject.toml, src/gafaelfawr/cli.py, src/gafaelfawr/database.py, src/gafaelfawr/main.py, src/gafaelfawr/operator/startup.py, tests/cli_test.py, tests/conftest.py, tests/data/schemas/9.6.1
Check whether the schema is current at all entry points, not just the FastAPI application startup, so that the other aspects of Gafaelfawr will also not start with an outdated database.
Fix the existing schema migration to use valid SQL. Add proper tests for schema updates, confirming the ability to upgrade from the last pre-Alembic schema version.
Add new gafaelfawr update-schema command to initialize the database if needed and then apply any missing Alembic migrations. Add new gafaelfawr validate-schema command that exits non-zero if the database has not been initialized or if the schema is not up to date.
=> DM-42384: Improve schema handling and testing

src/gafaelfawr/factory.py, src/gafaelfawr/storage/admin.py, src/gafaelfawr/storage/history.py, src/gafaelfawr/storage/token.py, tests/handlers/api_history_test.py
Now that SQLAlchemy 2.x has been released, we no longer need to import some things from sqlalchemy.future and can simplify imports.
=> DM-42627: Remove uses of sqlalchemy.future

docs/user-guide/openid-connect.rst
Document the correct return_uri setting for Chronograf, and remove the Kibana documentation since we no longer use it and are not testing this configuration.
=> DM-42384: Minor improvements to OpenID Connect documentation

changelog.d/20240222_115317_rra_DM_42384.md, src/gafaelfawr/main.py, tests/main_test.py, tests/operator/ingress_test.py
The check for whether the database schema was current during startup of the web application was never run because it was missing an await. Fix that and add a test.
=> DM-42384: Fix database schema check during startup

CHANGELOG.md, docs/index.rst, docs/user-guide/helm.rst, docs/user-guide/index.rst
Some operational documentation that is heavy on Argo CD actions or is closely entangled with Phalanx updates is documented on the Phalanx site. Add pointers to that documentation in multiple places.
=> DM-42627: Add more pointers to the Phalanx documentation

changelog.d/20240313_102609_rra_DM_43288a.md, docs/dev/internals.rst, src/gafaelfawr/operator/__init__.py, src/gafaelfawr/operator/health.py
Run the health check service as a Kopf probe. Mention other Phalanx improvements to Gafaelfawr's Helm chart in the change log.
=> DM-43288: Add Kopf health check

changelog.d/20240312_180104_rra_DM_43288.md, src/gafaelfawr/factory.py, src/gafaelfawr/services/firestore.py, src/gafaelfawr/services/health.py, src/gafaelfawr/services/ldap.py, src/gafaelfawr/services/userinfo.py
The health check tried to bypass the user info service, but that would require recreating all of the logic that the user info service already had and bypassed checking connectivity to Firestore. Instead, add uncached flags to the user info service and its underlying LDAP and Firestore services that make uncached requests for a proper health check, and use it.
=> DM-43288: Use user info service for health check

changelog.d/20240313_102609_rra_DM_43288a.md, src/gafaelfawr/models/health.py, src/gafaelfawr/operator/health.py, src/gafaelfawr/services/health.py
The Kubernetes operator doesn't need access to LDAP or Firestore, so checks that use that access will fail. Add a flag that allows the Kopf health checks to disable this.
=> DM-43288: Don't check LDAP and Firestore from Kopf

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, Makefile, docs/dev/development.rst, docs/user-guide/helm.rst, requirements/dev.in, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/config.py, src/gafaelfawr/models/auth.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/oidc.py, tox.ini
Use the tox-uv plugin to speed up management of the tox virtual environments. Fix lots of documentation warnings (mostly from using Markdown in model descriptions), and re-enable fatal warnings for documentation builds.
=> DM-43714: Switch to tox-uv, fix docs

docs/_rst_epilog.rst, docs/user-guide/helm.rst, docs/user-guide/provider.rst
Note at the start of the documentation for generic OpenID Connect that this support has been primarily tested with Keycloak. Also mention it in the page about authentication providers.
=> Add explicit mention of Keycloak to docs

Dockerfile
Update to Python 3.12.3 and switch base Debian images from bullseye to bookworm.
=> DM-44136: Update Docker base image

tests/handlers/api_tokens_test.py, tests/handlers/auth_logging_test.py, tests/handlers/login_github_test.py, tests/handlers/login_oidc_errors_test.py, tests/handlers/logout_test.py, tests/handlers/oidc_test.py, tests/providers/oidc_verifier_test.py, tests/support/logging.py
The necessary types for proper type-checking of tests are now exported from the top level of pytest. Remove the now-unneeded imports from _pytest, and refer to those types qualified with pytest, following pytest best practices.
=> DM-44136: Stop importing symbols from _pytest

examples/docker/gafaelfawr.yaml, examples/gafaelfawr-dev.yaml, src/gafaelfawr/config.py, src/gafaelfawr/models/kubernetes.py
Stop using the Safir CamelCaseModel base class and instead use the native Pydantic construction that does the same thing. Reject unknown configuration settings.
=> DM-44136: Switch to native Pydantic camel-case support

src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/dependencies/context.py, src/gafaelfawr/dependencies/return_url.py, src/gafaelfawr/handlers/analyze.py, src/gafaelfawr/handlers/api.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/cadc.py, src/gafaelfawr/handlers/internal.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/logout.py, src/gafaelfawr/handlers/oidc.py
Change the type annotations for all dependencies and handlers to use Annotated rather than putting the FastAPI magic functions in default values. Add * to force keyword arguments for these functions.
=> DM-44136: Use Annotated for dependencies and handlers

tests/cli_test.py, tests/config_test.py, tests/conftest.py, tests/main_test.py, tests/support/database.py
Lift various database helper functions that were scattered around into a module and call those functions to avoid some code duplication.
=> DM-44136: Move database test helper functions to module

tests/data/config/oidc-no-attrs.yaml.in, tests/handlers/login_oidc_test.py
Check that the LDAP attributes for various types of user information can be set to null, which suppresses looking up that data even if it is present in LDAP.
=> DM-44136: Add test for disabling LDAP attributes

changelog.d/20240520_165608_rra_DM_44269.md, src/gafaelfawr/config.py, tests/data/config/github.yaml
The default config.quota setting is an empty dictionary, which wasn't being parsed correctly. Add it to the list of configurations to trim if it's not set.
=> DM-44269: Fix configuration parsing of empty quota

changelog.d/20240521_074906_rra_DM_44269.md, src/gafaelfawr/config.py, tests/config_test.py, tests/data/config/scope-mismatch.yaml
Reject configuration files that assign scopes in groupMapping but do not define those scopes in knownScopes. Improve the configuration tests to check for a specific validation error, ensuring the tests don't accidentally fail due to some other configuration issue.
=> DM-44269: Cross-check groupMapping and knownScopes

changelog.d/20240521_162006_rra_DM_44468.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml
Add an authCacheDuration configuration option to GafaelfawrIngress, which tells Gafaelfawr to set the NGINX annotations that enable caching of the Gafaelfawr response for the specified length of time. The cache is automatically invalidated if the Cookie or Authorization HTTP headers change.
=> DM-44468: Add configuration for NGINX caching

changelog.d/20240522_152758_rra_DM_44490.md, src/gafaelfawr/operator/health.py, src/gafaelfawr/operator/tokens.py
Explicitly close async database sessions in the health check and token portions of the Kubernetes operator. (The ingress handler doesn't use the database.) Even with an async_scoped_session, the database session has to be explicitly removed or it will leak and eventually force the operator to crash and restart.
=> DM-44490: Close async database sessions in the operator

changelog.d/20240524_115108_rra_DM_44540.md, src/gafaelfawr/exceptions.py, tests/handlers/api_tokens_test.py
Return the more-correct 409 Conflict HTTP error code when a user attempts to duplicate a token name instead of the generic 422 input validation error.
=> DM-44540: Fix HTTP error code for duplicate token names

changelog.d/20240524_120600_rra_DM_44541.md, src/gafaelfawr/config.py, tests/config_test.py, tests/data/config/cilogon-test.yaml
The configuration refactoring in Gafaelfawr 11.0.0 accidentally discarded the enrollmentUrl setting for CILogon rather than copying it into the generated OpenID Connect provider configuration. Fix this and add a test.
=> DM-44541: Respect enrollmentUrl for CILogon

Makefile, changelog.d/20240814_105528_rra_DM_45518.md, docs/_rst_epilog.rst, docs/dev/internals.rst, docs/documenteer.toml, docs/user-guide/helm.rst, docs/user-guide/index.rst, docs/user-guide/metrics.rst, pyproject.toml, requirements/dev.txt, requirements/main.in, requirements/main.txt, src/gafaelfawr/cli.py, src/gafaelfawr/config.py, src/gafaelfawr/dependencies/context.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/main.py, src/gafaelfawr/metrics.py, src/gafaelfawr/models/state.py, src/gafaelfawr/services/token.py, src/gafaelfawr/storage/token.py, tests/conftest.py, tests/services/token_test.py, tests/storage/token_test.py, tox.ini
Add initial support for exporting OpenTelemetry metrics to a collector via insecure gRPC. The initial metrics only cover logins (counts of success, failure, enrollment redirects, and attempts, plus time to successful authentication), authentications where Gafaelfawr is delegating a token, and counts of active sessions and user tokens from database queries in the maintenance cron job.
Reset login state after an error so that any subsequent authentication attempts will generate a new, random state parameter. This also improves reporting of the login metrics.
=> DM-45518: Add support for OpenTelemetry metrics

pyproject.toml, ruff-shared.toml
Import the Ruff configuration from the current FastAPI Safir app template.
=> DM-45779: Switch to shared Ruff configuration

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml
Use a single global Python version for all CI actions and stop using a Python version matrix. Use a more robust way to trigger notifications when the periodic CI job fails. Use make update-deps to update dependencies rather than using neophile, since we're not using any of neophile's special abilities.
=> DM-45779: Update GitHub Actions to match current template

src/gafaelfawr/handlers/auth.py, src/gafaelfawr/util.py, tests/util_test.py
This is only needed for auth metrics, not login or state metrics, since the latter two already don't count mobu bot users since they don't do session logins and don't create user tokens.
=> DM-45779: Exclude mobu bot users from metrics

src/gafaelfawr/cli.py, src/gafaelfawr/database.py, src/gafaelfawr/main.py, src/gafaelfawr/operator/startup.py, tests/conftest.py, tests/support/selenium.py
The database password and Slack webhook can now be passed into Safir code as SecretStr, so drop now-unnecessary get_secret_value() method calls.
=> DM-45779: Drop unnecessary get_secret_value()

docs/user-guide/gafaelfawringress.rst, docs/user-guide/ingress-overview.rst
Mention setting a custom Authorization header when delegating tokens that way in the guide to request headers, reference the request header guide in the overview of ingresses, and promote the problem with application-returned 403 responses to a caution.
=> DM-45779: Improve documentation of headers

.github/workflows/ci.yaml
When building documentation from a ticket branch pull request, don't upload the newly-built documentation unless files in the docs/* directory have changed. This saves time and space for changes that only affect the generated API documentation.
=> DM-44567: Don't upload docs if they haven't changed

changelog.d/20240820_162506_rra_DM_45858.md, src/gafaelfawr/operator/startup.py, tests/support/kubernetes.py
Follow recommendations from a Reddit comment linked in the Kopf documentation to cap the worker limit at five. We do want to create Ingress objects in a timely fashion because we use them for labs, but it doesn't need to be immediate and we don't want to overwhelm the API server.
=> DM-45858: Cap Gafaelfawr Kopf workers at five

changelog.d/20240821_140900_rra_DM_45858.md, crds/ingress.yaml, docs/_rst_epilog.rst, docs/dev/release.rst, docs/user-guide/manual-ingress.rst, pyproject.toml, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/auth.py, src/gafaelfawr/models/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/auth_test.py, tests/operator/ingress_test.py
Add a top-level service configuration attribute to GafaelfawrIngress and a service parameter to the auth endpoint. Use this instead of delegate_to for logging. This is currently optional but will become mandatory in the future.
If internal token delegation is enabled in GafaelfawrIngress, the value of the service attribute in the delegation configuration must match the top-level service attribute. The service attribute inside the delegation configuration will be removed in the future.
If service and delegate_to are set as parameters to the auth endpoint, they must have the same values.
=> DM-45858: Add service parameter to the auth endpoint

crds/ingress.yaml, docs/dev/index.rst, docs/dev/kubernetes.rst
Add a development documentation page about the Kubernetes operator and document changes we want to make to the Gafaelfawr CRDs once we have a way to do conversion webhooks.
=> DM-45858: Document future CRD changes

.dockerignore, .gitignore, docs/api.rst, docs/conf.py, docs/documenteer.toml, src/gafaelfawr/cli.py, src/gafaelfawr/main.py, tox.ini
Use the new documenteer method for generating the REST API documentation rather than building openapi.json inside of tox.
Resync .dockerignore and .gitignore with the package templates and remove some old things that are no longer needed.
=> DM-46019: Switch to new documenteer REST API method

changelog.d/20240911_155549_rra_DM_46034a.md, docs/dev/development.rst, pyproject.toml, src/gafaelfawr/cli.py, src/gafaelfawr/database.py, src/gafaelfawr/dependencies/config.py, tests/cli_test.py, tests/data/schemas/10.0.0, tests/database_test.py, tests/support/constants.py
Add a new test that uses `alembic check` to ensure that the database schema hasn't changed.
To support maintaining the data files used by that test, add a new `gafaelfawr generate-schema` command that dumps the SQL commands required to generate the current schema. Document using that command to update the most recent schema in the test suite after adding a new schema migration.
=> DM-46034: Add a test that the database schema hasn't changed

pyproject.toml, src/gafaelfawr/schema/admin.py, src/gafaelfawr/schema/admin_history.py, src/gafaelfawr/schema/base.py, src/gafaelfawr/schema/subtoken.py, src/gafaelfawr/schema/token.py, src/gafaelfawr/schema/token_auth_history.py, src/gafaelfawr/schema/token_change_history.py
Use the new inheritance-based `DeclarativeBase` and the new field mapping syntax instead of `Column`. Rely on type annotations for schema information where possible.
=> DM-46034: Convert to the new SQLAlchemy ORM syntax

alembic.ini
Find the Alembic scripts relative to `alembic.ini` and fix how Ruff is invoked after creating Alembic migrations.
=> DM-46034: Update Alembic configuration

Dockerfile, Makefile, docs/dev/development.rst, requirements/dev.txt, requirements/main.txt, requirements/tox.txt, ui/package-lock.json
Switch to uv for Docker builds and enable its hash validation mode that only verifies hashes that are present. This allows dropping the update-deps-no-hashes Makefile target, since there's no longer a need to drop all hashes in order to have one dependency that isn't hashed (such as a Git dependency).
=> DM-46310: Use uv for Docker build, verify hashes

.pre-commit-config.yaml, alembic/env.py, docs/dev/release.rst, docs/documenteer.toml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/helm.rst, pyproject.toml, requirements/dev.txt, requirements/main.txt, requirements/tox.txt, src/gafaelfawr/cli.py, src/gafaelfawr/database.py, src/gafaelfawr/main.py, src/gafaelfawr/operator/startup.py, tests/conftest.py, tests/support/database.py, tox.ini, ui/package-lock.json
Remove the Alembic support code that has been lifted into Safir and call the functions in Safir instead. Depend on Safir 6.4.0, which added the Alembic support.
=> DM-46034: Use Alembic support code from Safir

changelog.d/20240919_154251_rra_DM_46399.md, src/gafaelfawr/config.py, tests/config_test.py, tests/data/config/bad-lifetime.yaml
Check that the configured token lifetime is at least as long as twice the minimum token lifetime so that we don't get weird redirect loops with very short token lifetimes.
=> DM-46399: Check that token lifetime is long enough

changelog.d/20240919_172648_rra_DM_46399.md, src/gafaelfawr/handlers/login.py, tests/handlers/login_github_test.py
If the authentication state is missing entirely, not incorrect, during return from authentication, the most likely explanation is that the user attempted multiple simultaneous logins and then finished the authentication in another browser window, thus invalidating the state.
In this case, redirect the user to their destination without further processing. If they did authentication separately, this is the (mostly) correct thing to do; they will go to the authenticated page, although their session might not be as currently as they would like.
If they're not authenticated, this will restart the authentication process with new state, which should be the correct thing to do. There is some risk of a redirect loop, but hopefully we won't go through that loop more than once, so browsers should …
=> DM-46399: Rework handling of missing state during login

crds/ingress.yaml, src/gafaelfawr/models/kubernetes.py
The base URL is now set in the global Gafaelfawr configuration by default, so baseUrl is now optional. Reflect that in the CRD and the model.
=> DM-46399: Make baseUrl optional in GafaelfawrIngress CRD

src/gafaelfawr/models/token.py, src/gafaelfawr/services/token_cache.py, src/gafaelfawr/storage/token.py, tests/services/oidc_test.py, tests/services/token_test.py
In preparation for exposing service information for internal tokens and using it for authorization decisions, add that data to Redis.
=> DM-46399: Add service of internal tokens to Redis

changelog.d/20240925_110256_rra_DM_46399.md, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/constants.py, src/gafaelfawr/handlers/ingress.py, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_test.py
When the authenticating token is an internal token with an associated service, include an X-Auth-Request-Service header in the response to the ingress, propagated to the incoming request, that includes the name of the associated service.
=> DM-46399: Add X-Auth-Request-Service HTTP header

changelog.d/20240925_144604_rra_DM_46399.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_test.py
Add the concept of a service-only ingress, which in addition to any other authorization requirements also requires the authentication token be a token issued to a particular service. Currently, this means an internal token obtained through a delegation request in its ingress, although in the future this may include other methods of associating a token with the service. The key point is that this will reject authentication directly from users, allowing services to be limited to requests from other services on behalf of users but not allow access from those same users directly.
Update some of the `GafaelfawrIngress` documentation to urge setting `config.service`, mark `config.delegate.internal.service` as deprecated, and otherwise update for recent changes.
=> DM-46399: Allow restricting ingresses to services

changelog.d/20241021_153026_rra_DM_47011.md, docs/user-guide/helm.rst
Document the new Phalanx `config.baseInternalUrl` Helm setting for Gafaelfawr to override its understanding of its internal URL.
=> DM-47011: Document config.baseInternalUrl setting

src/gafaelfawr/cache.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/models/state.py, src/gafaelfawr/providers/github.py, src/gafaelfawr/providers/oidc.py
Python 3.12 added a way to explicitly mark functions as being overrides using a decorator. This improves the type checking. Use that annotation where appropriate.
=> DM-47148: Use @override annotations where appropriate

changelog.d/20241025_160624_rra_DM_47148.md, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml
Add the label `app.kubernetes.io/managed-by` with value `Gafaelfawr` to all `Ingress` resources created by Gafaelfawr.
=> DM-47148: Add label to Gafaelfawr-managed ingresses

changelog.d/20241028_133552_rra_DM_47148.md, docs/user-guide/openid-connect.rst, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/models/oidc.py, tests/handlers/oidc_test.py
In the OpenID Connect server, add `client_secret_basic` support for authentication to the token endpoint. This is the recommended authentication method and some clients (specifically SATOSA, used by the Brazilian IDAC) do not successfully negotiate `client_secret_post`.
=> DM-47148: Add support for `client_secret_basic`

CHANGELOG.md, changelog.d/20241028_150742_rra_DM_47148.md, docs/user-guide/metrics.rst, src/gafaelfawr/events.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/util.py, tests/util_test.py
Log separate metrics for bot authentications and user authentications. Remove the special case for mobu bot users, since they can now be counted as regular bot users.
=> DM-47148: Separate bot users in auth events

changelog.d/20241118_171429_rra_DM_47646.md, src/gafaelfawr/services/oidc.py, tests/handlers/oidc_test.py
Avoid double slashes in the endpoint URLs returned by `/.well-known/openid-configuration`, fixing a bug introduced in Gafaelfawr 12.0.0. The stringification of the base URL now always includes a trailing slash for URLs with no path, which resulted in a doubled slash and an invalid URL.
=> DM-47646: Fix double slashes in openid-configuration URLs

src/gafaelfawr/config.py, src/gafaelfawr/models/admin.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/models/token.py, src/gafaelfawr/storage/admin.py, src/gafaelfawr/storage/history.py, src/gafaelfawr/storage/token.py
Where `model_config` settings for Pydantic models are needed, move them to the top of the class to make them more obvious. Remove the ones that enable parsing from object attributes in favor of passing that flag directly into `model_validate` in the storage layer.
=> DM-47646: Move or remove model_config settings

pyproject.toml
Black is never used recursively for reformatting any more since Gafaelfawr has switched to Ruff, so the file exclusion list is no longer needed.
=> DM-47646: Remove unnecessary Black configuration

pyproject.toml, ruff-shared.toml
Drop Alembic overrides from `pyproject.toml` since those are now included in the generic file.
=> DM-47646: Updated shared Ruff configuration file

changelog.d/20241120_164500_rra_DM_47716_queue.md, docs/documenteer.toml, src/gafaelfawr/factory.py, src/gafaelfawr/storage/firestore.py
Stop creating a Google Firestore client for every request, since creating the client does some authentication setup. Instead, create a single client and reuse it for the lifetime of the process.
=> DM-47716: Avoid creating Firestore clients on every request

changelog.d/20241120_145516_rra_DM_47716.md, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/services/token_cache.py, tests/handlers/api_history_test.py, tests/services/token_cache_test.py, tests/services/token_test.py
The pattern of doing database transaction management within the handlers meant that a database transaction was created in the hot path of ingress auth requests if delegated tokens were requested. Move the transaction management into the token cache service so that the transaction is only created if database activity is required.
=> DM-47716: Move token cache transaction management

src/gafaelfawr/cli.py, src/gafaelfawr/database.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/api.py, src/gafaelfawr/handlers/login.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/services/admin.py, src/gafaelfawr/services/health.py, src/gafaelfawr/services/kubernetes.py, src/gafaelfawr/services/token.py, tests/handlers/api_admins_test.py, tests/handlers/api_history_test.py, tests/handlers/api_tokens_test.py, tests/handlers/cadc_test.py, tests/handlers/ingress_test.py, tests/handlers/internal_test.py, tests/handlers/login_github_test.py, tests/handlers/oidc_test.py, tests/handlers/quota_test.py, tests/operator/tokens_test.py, tests/services/admin_test.py, tests/services/oidc_test.py, tests/services/token_test.py, tests/storage/token_test.py, tests/support/selenium.py, tests/support/tokens.py
Stop doing database transaction management in the handlers and instead move all transaction management into the service layer. This simplifies the test suite considerably and makes the handlers simpler and cleaner.
This requires moving the addition of the `admin:token` scope to new authentications by admins into the token service layer, which is probably where it always belonged.
In a few cases, the code will open more transactions than it did before, but all of those cases should be slow paths.
=> DM-47716: Move all session management to service layer

changelog.d/20241122_102407_rra_DM_47760.md, src/gafaelfawr/services/oidc.py, tests/handlers/oidc_test.py
Always omit the `data_rights` claim in OpenID Connect server tokens if the user has no data rights, rather than sometimes omitting it and sometimes setting it to the empty string.
=> DM-47760: Uniformly handle claim for no data rights

changelog.d/20241122_105538_rra_DM_47716.md, src/gafaelfawr/handlers/ingress.py
Move metrics reporting for hot-path authentication events to a background task so that it happens in parallel with the HTTP response.
=> DM-47716: Move auth metrics reporting to a background task

changelog.d/20241122_115147_rra_DM_47760.md, src/gafaelfawr/handlers/oidc.py, tests/handlers/oidc_test.py
Allow a client to present an internal token to the `/auth/openid/userinfo` endpoint. CADC's authenticator finds the userinfo endpoint via OpenID Connect configuration and presents whatever token it has to that endpoint, so this allows it to use the regular userinfo endpoint.
This will hopefully allow us to drop the `/auth/cadc/userinfo` route in a future release.
=> DM-47760: Allow internal tokens on the OIDC userinfo route

changelog.d/20241122_105538_rra_DM_47716.md, src/gafaelfawr/handlers/ingress.py
This reverts commit 2d0ea937069a8fe98371a5c19f74b030f0488c11. The problem will be fixed in the next release of Safir in the underlying metrics code by backgrounding the write inside the metrics layer.
=> DM-47716: Revert "Move auth metrics reporting to a background task"

docs/documenteer.toml, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/util.py, tests/util_test.py
Remove `parse_timedelta`, which was dead code since its usage had previously been replaced by the Safir type. Change the one remaining place using `normalize_timedelta` to use `SecondsTimedelta` from Safir and delete that code as well.
=> DM-47789: Use Safir timedelta validation types

docs/documenteer.toml, src/gafaelfawr/handlers/api.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/models/token.py, src/gafaelfawr/models/userinfo.py, src/gafaelfawr/pydantic.py
Convert the Gafaelfawr `Timestamp` data type to be based on the Safir `UtcDatetime` instead of using the `normalize_datetime` function, which will hopefully be deprecated in the future. Convert some other `datetime` model fields to `UtcDatetime`.
Convert one remaining `timedelta` query parameter to use `SecondsTimedelta` so that Pydantic will do the validation.
=> DM-47789: Convert datetime and timedelta to Safir types

tests/cli_test.py, tests/main_test.py, tests/schema_test.py, tests/support/database.py
Now that Safir provides an implementation of `drop_database`, use that version and delete the one in Gafaelfawr.
=> DM-47789: Use drop_database from Safir

src/gafaelfawr/models/health.py, src/gafaelfawr/models/history.py, src/gafaelfawr/pydantic.py, src/gafaelfawr/util.py, tests/handlers/api_tokens_test.py, tests/support/logging.py
Using Pydantic `IPvAnyAddress` still appears to be more trouble than it's worth, but at least the internal IP address handling that produces a `str` can be moved into a Pydantic type rather than needing the more awkward field validator syntax.
=> DM-47789: Move IP address normalization into a type

docs/documenteer.toml, src/gafaelfawr/models/history.py, src/gafaelfawr/models/token.py, src/gafaelfawr/pydantic.py, src/gafaelfawr/util.py
Wrap the scopes validation in a Pydantic type to make it easier to use and avoid the field validator syntax.
=> DM-47789: Move scopes validation into a Pydantic type

changelog.d/20241210_164212_rra_DM_47986.md, src/gafaelfawr/operator/health.py
The object returned from the health probe for Kopf couldn't be serialized as JSON. This was harmless but produced error messages in the logs. Return the model dumped in JSON format instead.
=> DM-47986: Fix JSON serialization of Kopf healt probe

changelog.d/20241211_105613_rra_DM_47986.md, src/gafaelfawr/handlers/ingress.py, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_test.py
Allow an authenticated `GafaelfawrIngress` to have an empty list of required scopes. This is useful for the `onlyService` use case when any scope is permitted but the requesting token must be a delegated token for one of the listed services. This was already valid in the CRD, but previously resulted in a 422 error from Gafaelfawr and a 500 error from ingress-nginx.
=> DM-48088: Allow an empty list of required scopes

src/gafaelfawr/cache.py, src/gafaelfawr/middleware/state.py, src/gafaelfawr/models/history.py, src/gafaelfawr/storage/kubernetes.py
Convert all generics to the new Python 3.12 syntax, which no longer requires `TypeVar` or `ParamSpec`. Sphinx doesn't like the combination of this syntax and `from __future__ import annotations`, so remove that line from the files that use this syntax.
=> DM-48196: Switch to new generics syntax

src/gafaelfawr/pydantic.py
mypy now supports the `type` keyword, so use it instead of `TypeAlias` when defining new types.
=> DM-48196: Use type keyword instead of TypeAlias

docs/documenteer.toml
Point to the correct Sphinx bug to explain why we're excluding `Path` from Sphinx nitpicks.
=> DM-48196: Update comment for Sphinx Path exclusion

changelog.d/20250107_161611_rra_DM_48326.md, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/output/ingresses.yaml, tests/operator/ingress_test.py
ingress-nginx 4.12.0 has added a restrictive regex filter on the auth-url annotation that rejects `%` characters and therefore all escaped characters in URLs. It does allow `:` unescaped, and leaving `:` unescaped in query parameters is safe according to the relevant RFC, so add `:` to the set of safe characters that do not need to be escaped.`
=> DM-48326: Stop escaping `:` in Ingress auth-url

src/gafaelfawr/models/history.py, src/gafaelfawr/storage/history.py, src/gafaelfawr/storage/token.py
To avoid confusion between other models and SQLAlchemy schema classes, uniformly rename schema tables imported into other modules by adding a `SQL` prefix.
=> DM-48319: Rename symbols imported from schema module

docs/documenteer.toml, pyproject.toml, src/gafaelfawr/exceptions.py, src/gafaelfawr/storage/firestore.py
The Firestore library sometimes throws `ValueError` when trying to roll back a transaction, claiming there is no transaction ID. It's not clear what's causing this, but at least catch the error and transform it into a `FirestoreError` so that the reporting is better.
=> DM-48319: Catch ValueError exceptions from Firestore

src/gafaelfawr/exceptions.py, src/gafaelfawr/models/state.py, src/gafaelfawr/models/token.py
The user's state information, stored in a cookie, was previously implemented as a dataclass with hand-written serialization and deserialization code. Replace this with a Pydantic model and validators and let Pydantic do the JSON serialization and deserialization.
This required making `InvalidTokenError` inherit from `ValueError` as well as its current parent so that Pydantic would accept exceptions thrown by validation and process them correctly.
=> Convert state handling to Pydantic models

src/gafaelfawr/models/kubernetes.py, tests/data/kubernetes/output/ingresses.yaml, tests/operator/ingress_test.py
The serialization order of the parameters to the `/auth` route when generating an `Ingress` was somewhat random based on when features were added. Serialize in the order of the model attributes instead (which is mostly alphabetical).
=> Serialize /auth parameters in model order

.pre-commit-config.yaml, CHANGELOG.md, changelog.d/20250108_223210_rra_DM_48326.md, requirements/dev.txt, requirements/main.txt, ruff-shared.toml, src/gafaelfawr/cli.py, src/gafaelfawr/services/token.py, ui/package-lock.json
Update Python, pre-commit, and JavaScript dependencies and the shared Ruff configuration file. Apply new Ruff fixes. Collect change log entries for the 12.3.2 release.
=> Prepare 12.3.2 release

changelog.d/20250110_124013_rra_DM_48387.md, src/gafaelfawr/handlers/login.py, tests/handlers/login_github_test.py
If the user returns to the login route without login state and no return URL is set (which will be the common case), redirect them to the after logout URL instead of returning a 403 error. Often this means the user previously authenticated via another tab and is now logged on, but we have lost the return URL and do not know where to send them. Returning the error is more confusing and often causes the user to attempt to reload the error page, which then fails.
=> DM-48387: Send users with no login state to after logout

changelog.d/20250110_143131_rra_DM_48390.md, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, tests/conftest.py, tests/handlers/oidc_test.py, tests/services/oidc_test.py, tests/services/token_cache_test.py, tests/services/token_test.py, tox.ini
Add a separate Redis client and connection pool for an ephemeral Redis instance and move OpenID Connect authentication codes into that Redis, rather than storing them in the same Redis as persistent data such as tokens. This ephemeral Redis will soon be used for rate limit data as well.
=> DM-48390: Separate persistent and ephemeral Redis

src/gafaelfawr/handlers/ingress.py
If any errors are encountered while trying to check for rate limiting, report them only in the error log and fail open (do not reject the request).
=> DM-48390: Suppress errors in rate limiting

docs/_rst_epilog.rst, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/userinfo.py, tests/handlers/ingress_rate_test.py, tests/handlers/ingress_test.py
Return rate limiting information in HTTP headers for all authenticated ingress responses. The headers sent match those used by GitHub's rate limiting implementation.
=> DM-48390: Add rate limiting headers to ingress responses

changelog.d/20250114_135624_rra_DM_48390.md, src/gafaelfawr/config.py, src/gafaelfawr/services/userinfo.py, tests/data/config/github-quota.yaml, tests/handlers/ingress_rate_test.py
Add a `bypass` key to the quota configuration that lists one or more groups. Any member of one of those groups ignores all quotas and will never have a quota set.
=> DM-48390: Add support for bypassing quota

src/gafaelfawr/config.py, src/gafaelfawr/models/userinfo.py, src/gafaelfawr/services/userinfo.py
In preparation for supporting quota overrides, move calculation of quotas to a method on the `QuotaConfig` model. (Making it a class constructor on the `Quota` model becomes awkward due to circular imports.)
=> DM-48432: Move quota calculation to QuotaConfig model

changelog.d/20250114_155651_rra_DM_48390.md, docs/user-guide/helm.rst, src/gafaelfawr/config.py, src/gafaelfawr/models/userinfo.py, tests/data/config/github-quota.yaml, tests/handlers/quota_test.py
Add a flag to the notebook quota indicating whether the user should be allowed to spawn a notebook, defaulting to true. This may be set to false for a specific group (or, later, a quota override) to indicate that user should not be allowed to spawn notebooks.
This field is calculated and returned by Gafaelfawr but is not enforced by it. It will be read by Nublado (specifically the Nublado controller).
=> DM-48390: Add support for disallowing notebook spawns

changelog.d/20250116_152452_rra_DM_48432.md, docs/dev/internals.rst, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, src/gafaelfawr/handlers/api.py, src/gafaelfawr/models/quota.py, src/gafaelfawr/models/userinfo.py, src/gafaelfawr/services/userinfo.py, src/gafaelfawr/storage/quota.py, tests/handlers/ingress_rate_test.py, tests/handlers/quota_test.py
Add a new REST API to set, retrieve, and delete quota overrides. Apply those overrides on top of the configured quotas. The overrides are stored in Redis and retrieved on every request currently; we will see if that's too slow and needs caching.
=> DM-48432: Add support for quota overrides

docs/user-guide/headers.rst, docs/user-guide/index.rst, src/gafaelfawr/constants.py, src/gafaelfawr/handlers/ingress.py, tests/handlers/ingress_rate_test.py
Add the necessary lines to the ingress-nginx snippet to set variables needed by the rate limiting response. Fix the rate limiting ingress response to use 403 and put the status code and body in the headers to work with the integration.
Document the rate limiting headers set by Gafaelfawr.
=> DM-48495: Add rate limiting integration with nginx

src/gafaelfawr/auth.py
In `generate_challenge`, change the body of the error to be a list of errors rather than a single error, following the error model used and declared elsewhere in Gafaelfawr.
=> DM-48495: Return a list of errors from auth failures

src/gafaelfawr/constants.py, src/gafaelfawr/factory.py
Separate the pool size for the ephemeral Redis pool from the persistent Redis pool and add a separate pool size for the rate limiting pool (which alas uses a different Redis client library). Add timeout and pool size settings for the Redis underlying the limits library, but for now keep the same retry implementation.
=> DM-48495: Tweak Redis connection pool settings

docs/user-guide/gafaelfawringress.rst
Warn that `authCacheDuration` in `GafaelfawrIngress` is incompatible with rate limiting since the cached requests will not count against rate limits.
=> DM-48622: Warn about authCacheDuration and rate limiting

docs/_rst_epilog.rst, docs/user-guide/headers.rst, docs/user-guide/helm.rst, docs/user-guide/index.rst, docs/user-guide/quotas.rst
Add a separate page about quotas with some additional background, and improve the Helm chart documentation for how to configure quotas.
=> DM-48622: Add more quota documentation

changelog.d/20250204_143146_rra_DM_48786.md, src/gafaelfawr/handlers/api.py, tests/handlers/quota_test.py
The longer-term plan is for squareone to warn if any quota overrides are in place, which will require the ability to retrieve the overrides for any authenticated user. Change the permissions on `GET` of the overrides to any authenticated user, keeping the admin permissions on `PUT` and `DELETE`, and add a test.
=> DM-48786: Allow regular users to get quota overrides

changelog.d/20250204_164948_rra_DM_48786.md, docs/user-guide/metrics.rst, src/gafaelfawr/events.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/userinfo.py, tests/data/config/github-quota.yaml, tests/handlers/ingress_logging_test.py
In the `auth_user` and `auth_bot` metrics events, add the total quota and the number of requests within the current time window if the request is subject to an API quota. If the request is rejected due to exceeding an API quota, log a new `rate_limit` metrics event.
=> DM-48786: Add quota information to metrics events

changelog.d/20250205_133812_rra_DM_48786.md, docs/user-guide/logging.rst, src/gafaelfawr/handlers/ingress.py, tests/handlers/ingress_logging_test.py
Add quota information to successful authorization log messages, if applicable. Change the order of logging so that creation of internal and notebook tokens is logged before the successful authorization, reflecting the true order of events. Add the service to the logging context.
Add a log message when a request is rejected due to rate limiting.
=> DM-48786: Log quota information

changelog.d/20250205_161516_rra_DM_48802.md, docs/user-guide/quotas.rst, src/gafaelfawr/handlers/api.py, src/gafaelfawr/handlers/ingress.py, tests/handlers/ingress_rate_test.py
If the API quota for the user for the target service is 0, treat that as an administrative block and reject the access with a 403 error instead of a 429 error.
=> DM-48802: Treat an API quota of 0 as an administrative block

changelog.d/20250210_131646_rra_DM_48870.md, src/gafaelfawr/config.py
The introduction of rate limiting support added a new Redis interface via the limits library which requires a URL. When constructing that URL with a Redis password, Gafaelfawr was not properly escaping the password. Add URL encoding.
=> DM-48870: Escape the Redis password in URLs

CHANGELOG.md, src/gafaelfawr/config.py, tests/config_test.py
Correct a serious bug in escaping of Redis passwords introduced in the previous release and add a change log for the 12.5.2 release.
=> DM-48870: Fix escaping of Redis passwords

changelog.d/20250226_150901_rra_DM_49149.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/operator/ingress.py, tests/data/kubernetes/input/ingress-error-cookies.yaml, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_test.py, tests/models/kubernetes_test.py
Add a new configuration setting, `config.allowCookies`, for a `GafaelfawrIngress`. If set to fale, require token authentication via an `Authorization` header and ignore any cookies. This protects against some CSRF attacks since the attacker cannot use existing browser cookies to make authenticated cross-site requests.
=> DM-49149: Allow rejecting cookie authentication to ingresses

changelog.d/20250226_170821_rra_DM_49149.md, docs/documenteer.toml, src/gafaelfawr/config.py, src/gafaelfawr/main.py, src/gafaelfawr/middleware/state.py
Make the Gafaelfawr configuration responsible for determining what flags to pass to `fastapi.Response.set_cookie` in preparation for adding more complex logic for domain cookies. Always force the cookie to be secure and drop the logic intended to allow local development instances, which have not been supported for some time.
=> DM-49149: Move cookie parameters into configuration

.github/workflows/ci.yaml, alembic/gafaelfawr.yaml, changelog.d/20250226_180120_rra_DM_49149.md, docs/user-guide/helm.rst, docs/user-guide/ingress-overview.rst, src/gafaelfawr/config.py, tests/conftest.py, tests/data/config/bad-admin.yaml, tests/data/config/bad-groups.yaml, tests/data/config/bad-lifetime.yaml, tests/data/config/bad-log-level.yaml, tests/data/config/bad-scope.yaml, tests/data/config/both-providers.yaml, tests/data/config/cilogon-test.yaml, tests/data/config/cilogon.yaml, tests/data/config/github-oidc-server.yaml, tests/data/config/github-quota.yaml, tests/data/config/github.yaml, tests/data/config/missing-scope.yaml, tests/data/config/no-provider.yaml, tests/data/config/oidc-claims.yaml, tests/data/config/oidc-enrollment.yaml, tests/data/config/oidc-firestore.yaml, tests/data/config/oidc-no-attrs.yaml, tests/data/config/oidc-no-memberdn.yaml, tests/data/config/oidc-subdomain.yaml, tests/data/config/oidc.yaml, tests/data/config/scope-mismatch.yaml, tests/data/config/selenium.yaml, tox.ini
Stop allowing the HTTP authentication realm to be configured separately, since this was never used in Phalanx. Instead, always set the authentication realm to the hostname of the Gafaelfawr base URL.
=> DM-49149: Drop support for the realm config option

changelog.d/20250303_152128_rra_DM_49149.md, docs/user-guide/administrators.rst, docs/user-guide/gafaelfawringress.rst, docs/user-guide/helm.rst, src/gafaelfawr/config.py, src/gafaelfawr/dependencies/return_url.py, tests/data/config/github-subdomain.yaml, tests/handlers/login_github_test.py, tests/handlers/logout_test.py
Allow Gafaelfawr to work across subdomains that are all child domains of the base URL by accepting a new `allowSubdomains` configuration parameter and, if it is set, setting domain-scoped cookies instead of host-scoped cookies. Adjust the validation of return URLs accordingly, permitting return URLs to a subdomain if subdomains are allowed.
Restructure the Helm chart documentation to avoid the meaningless "Basic settings" heading and improve grouping of similar things.
=> DM-49149: Add support for domain-scoped cookies

changelog.d/20250303_180647_rra_DM_49149.md, docs/user-guide/gafaelfawringress.rst, src/gafaelfawr/exceptions.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingress-error-host.yaml, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/operator/ingress_test.py
Unless the `GafaelfawrIngress` is anonymous or disables cookie authentication, reject hosts in ingress rules that do not match the host of the Gafaelfawr base URL or, if `config.allowSubdomains` is set, is a subdomain of that host. Such ingresses will never work with browser cookies and may produce confusing redirect loops.
=> DM-49149: Check the hosts of ingress rules

src/gafaelfawr/auth.py, src/gafaelfawr/config.py, src/gafaelfawr/dependencies/return_url.py, src/gafaelfawr/services/kubernetes.py, tests/handlers/ingress_test.py, tests/handlers/oidc_test.py, tests/support/headers.py
Rather than having a separate config property for the domain, make a config property for `base_hostname` that does the check required by mypy because `HttpUrl` doesn't work well with typing. Use that instead of accessing the `host` attribute of `config.base_url` directly.
=> DM-49149: Rework obtaining the base hostname internally

changelog.d/20250304_151908_rra_DM_49149.md, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/services/kubernetes.py, tests/data/kubernetes/input/ingress-error-cookies.yaml, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/models/kubernetes_test.py, tests/operator/ingress_test.py
Remove all remaining support for `config.baseUrl` in `GafaelfawrIngress` and ignore that setting if it is present. The one URL derived from that value (the login URL to which the user is redirected optionally if logged out) is now set only from the global Gafaelfawr configuration setting.
=> DM-49149: Ignore baseUrl in GafaelfawrIngress

changelog.d/20250304_184003_rra_DM_49315.md, changelog.d/20250305_154010_rra_DM_49315.md, crds/ingress.yaml, docs/user-guide/gafaelfawringress.rst, docs/user-guide/helm.rst, docs/user-guide/logging.rst, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/kubernetes.py, tests/data/config/github-subdomain.yaml, tests/data/kubernetes/input/ingresses.yaml, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_logging_test.py, tests/handlers/ingress_test.py, tests/operator/ingress_test.py
Add a new setting to `GafaelfawrIngress` named `config.userDomain` that, if set to true, requires that the last component of the request URL match the authenticated username. This is intended for use with per-user subdomains, such as Jupyter labs with JavaScript origin isolation. In this case, as an additional sanity check, also require that the hostname in the request be a subdomain of Gafaelfawr's base domain.
=> DM-49315: Add support for per-user domain authorization

src/gafaelfawr/dependencies/return_url.py, tests/handlers/login_github_test.py, tests/handlers/logout_test.py
If subdomain support was enabled and the return URL exactly matched the parent domain, the URL was incorrectly rejected. Fix the logic of the check.
=> DM-49329: Fix return URL checking

changelog.d/20250305_171727_rra_DM_49315.md, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/services/kubernetes.py, tests/conftest.py, tests/data/kubernetes/output/ingresses.yaml, tests/handlers/ingress_test.py, tests/selenium/tokens_test.py
Deploying Nublado with user subdomains revealed that Gafaelfawr had always been blocking `OPTIONS` requests to authenticated ingresses. It did not special-case the `OPTIONS` method and expected the request to contain normal authentication credentials, but the CORS pre-flight specification says that the `OPTIONS` request must not include credentials.
Special-case `OPTIONS` requests (using the `X-Original-Method` header set by ingress-nginx to detect what method the request used) and treat them as anonymous requests, always authorizing them.
=> DM-49329: Always authorize OPTIONS requests

src/gafaelfawr/config.py, src/gafaelfawr/dependencies/return_url.py, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/services/kubernetes.py, tests/operator/ingress_test.py
We had three separate places where hostnames were checked to see if they were either the base hostname or (if subdomain support is enabled) a subdomain. Move this code to be a method on the `Config` object so that there's only one copy of it.
=> DM-49329: Refactor hostname checking code

changelog.d/20250306_123621_rra_DM_49347.md, docs/user-guide/cors.rst, docs/user-guide/index.rst, docs/user-guide/ingress-overview.rst, src/gafaelfawr/auth.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/handlers/ingress.py, tests/handlers/ingress_test.py
Block all cross-origin `OPTIONS` requests unless the origin matches the hostname of the Gafaelfar base URL or, if subdomain support is enabled, is some subdomain of the hostname of the base URL. Reject `OPTIONS` requests without `Origin` headers with a 404 error.
=> DM-49347: Block cross-origin OPTIONS requests

.pre-commit-config.yaml, pyproject.toml, src/gafaelfawr/main.py, src/gafaelfawr/models/history.py, src/gafaelfawr/operator/startup.py, src/gafaelfawr/operator/tokens.py, tests/conftest.py, tests/pages/base.py, tests/selenium/tokens_test.py, tests/support/selenium.py, ui/package-lock.json, uv.lock
seleniumwire has been orphaned and is no longer maintained. Instead of using it to inject an authentication cookie, create a special route injected by the test suite for Selenium testing that sets an authentication cookie and visit it automatically. This allows dropping the seleniumwire dependency and a bunch of workarounds that were required to keep it.
Update dependencies and inject a structlog logger into the memo for Kopf runners so that the token operator can log properly and avoid a Ruff diagnostic.
=> DM-49495: Drop seleniumwire test dependency

scripts/install-dependency-packages.sh
Now that the Docker build is using a cache for apt metadata, it's no longer necessary to call `apt-get update` again when installing packages needed for building Python dependencies.
=> DM-50042: Remove unnecessary apt-get update in Docker build

.pre-commit-config.yaml
Ruff now uses `ruff-check` as the id for the linter, rather than a bare `ruff`. Adjust `.pre-commit-config.yaml` accordingly.
=> DM-51521: Change Ruff checker pre-commit id

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, Dockerfile, Makefile, scripts/install-dependency-packages.sh, scripts/update-uv-version.sh, ui/package-lock.json, uv.lock
Update the GitHub CI templates to more closely follow the new proposed FastAPI Safir app template, and add `Makefile` code to update the uv version in the GitHub CI jobs and `Dockerfile` after updating the pinned version.
=> DM-51521: Update to new uv-based templates

changelog.d/20250701_151955_rra_DM_51679.md, src/gafaelfawr/constants.py, tests/handlers/login_oidc_test.py
Fix the group name validation regex so that it accepts all valid usernames, specifically including usernames that start with numbers. Otherwise, if `addUserGroup` is enabled, a user with a username starting with digits would trigger internal validation errors. If that user's token was the most recent created, this could in turn cause health check failures.
=> DM-51679: Fix group regex to allow all valid usernames

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, Dockerfile, docs/dev/internals.rst, docs/documenteer.toml, pyproject.toml, ui/package-lock.json, uv.lock
Update Python, pre-commit, and JavaScript dependencies.
Adapt the documenteer 2.0.0 release, which allows removal of some ignore rules and some dependencies. Unfortunately, it requires disabling inherited fields in Pydantic model documentation and can no longer cross-reference base Pydantic model classes, so those errors have to be ignored.
=> DM-51810: Update dependencies

changelog.d/20250714_154548_rra_rate_limit.md, docs/user-guide/helm.rst, docs/user-guide/metrics.rst, docs/user-guide/quotas.rst, src/gafaelfawr/handlers/ingress.py, src/gafaelfawr/models/quota.py, tests/handlers/ingress_logging_test.py, tests/handlers/ingress_rate_test.py
Practical experience with setting rate limits has found that it is sufficiently undesirable to block a user for up to 15 minutes that we don't set rate limits for fear of creating that outcome. Given that and the easier mental math involved in using a more regular interval, reduce the API rate limit interval to one minute and interpret API rate limits as requests per minute. One implication is that the rate limit (apart from total administrative blocks) cannot be less than one request per minute.
=> DM-51810: Base API rate limits on requests per minute

docs/user-guide/quotas.rst
Add several examples of retrieving, setting, and deleting quota overrides from the command line using cURL.
=> DM-51810: Add examples of quota overrides from command line

.github/workflows/ci.yaml, changelog.d/20250715_153805_rra_DM_51818.md, docs/user-guide/helm.rst, docs/user-guide/quotas.rst, src/gafaelfawr/models/quota.py, src/gafaelfawr/services/userinfo.py, tests/data/config/github-quota.yaml, tests/handlers/quota_test.py
Add a new TAP quota element to user quotas, with the same group math and override support as API quotas. Currently, there is only one quota, controlling the allowed number of concurrent queries, but the data structure is extensible so that other quota information (result size, perhaps) can be added in the future.
=> DM-51818: Add TAP quotas

changelog.d/20250718_090750_rra_DM_51859.md, src/gafaelfawr/handlers/ingress.py, tests/data/config/github-quota.yaml, tests/handlers/ingress_logging_test.py, tests/handlers/ingress_rate_test.py, tests/handlers/quota_test.py
Service was incorrectly omitted from the rate limit key, causing a bug where usage counters were merged between different services with the same API quota for a given user. API services with different quotas were still kept separate. Fix this by explicitly adding the service name to the rate limit key.
=> DM-51859: Add service to rate limit key

.github/workflows/ci.yaml
The 14.0.0 release did not correctly build and upload documentation because the release push itself didn't modify any documentation files. Add `CHANGELOG.md` to the list of documentation files to catch this case, and also ensure documentation is published on workflow dispatch events.
=> DM-51521: Build docs when CHANGELOG.md changes

docs/dev/development.rst
Add explicit documentation for running a particular tox environment, and remove a remaining reference to Black and isort.
=> DM-51521: Update development documentation

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250808_150548_rra_DM_52140.md, scripts/update-uv-version.sh, ui/package-lock.json, ui/package.json, uv.lock
Collect the change log for the 14.0.1 release. Update Python, pre-commit, and JavaScript dependencies. Update the script to update the uv version to the latest version from the FastAPI Safir app template.
=> DM-52140: Prepare 14.0.1 release
