lsst-sqre/gafaelfawr

kube/template/ing/jwt-authorizer-token-ingress.yml, kube/template/ing/jwt-authorizer.yml, kube/template/ing/oauth2-proxy.yml, kube/template/ing/well-known-jwks.yml, kube/template/init.sh, kube/template/secret/jwt-authorizer.yml, kube/template/secret/oauth2-client.yml
Fix some of the config templating and TLS secrets
=> Config template fixes

docs/api.rst, example/authorizer.yaml, kube/template/secret/jwt-authorizer.yml, pyproject.toml, rootfs/etc/jwt-authorizer/authorizer.yaml, src/jwt_authorizer/analyze.py, src/jwt_authorizer/app.py, src/jwt_authorizer/authnz.py, src/jwt_authorizer/config.py, src/jwt_authorizer/defaults.yaml, src/jwt_authorizer/session.py, src/jwt_authorizer/tokens.py, src/jwt_authorizer/util.py, tests/analyze_test.py, tests/app_auth_test.py, tests/app_tokens_handle_test.py, tests/app_tokens_new_test.py, tests/app_tokens_test.py, tests/authnz_test.py, tests/conftest.py, tests/session_test.py, tests/tokens_test.py, tests/util.py, tests/util_test.py
- Move more code into the Ticket, Session, and SessionStore classes
- Reduce duplicate code in test suite setup
- Remove unused configuration parameters
- Remove unnecessary complexity in how authorization checks are done
- Add tests for all the major code paths
- Refactor user-generated token issuance into a TokenStore class
=> [DM-23942] Refactor JWT Authorizer

CHANGELOG.rst, src/gafaelfawr/config.py, src/gafaelfawr/providers/oidc.py, tests/handlers/login_oidc_test.py, tests/setup.py, tests/support/http_session.py
- Report errors from the upstream OIDC provider in more detail
- Add testing for the error handling paths and improve OIDC test setup
=> [DM-24597] Report upstream OIDC errors

CHANGELOG.rst, docker-compose.yaml, docs/api.rst, docs/conf.py, docs/configuration.rst, docs/install.rst, examples/gafaelfawr-dev.yaml, examples/gafaelfawr-github.yaml, examples/gafaelfawr-oidc.yaml, examples/secrets/redis-password, src/gafaelfawr/app.py, src/gafaelfawr/config.py, src/gafaelfawr/settings.py, tests/app_test.py, tests/settings/redis-password.yaml.in
- Add support for password-protected Redis
- Clean up some documentation issues I noticed while adding that support
=> [DM-26078] Support Redis passwords

CHANGELOG.rst, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/util.py, tests/handlers/oidc_test.py, tests/handlers/well_known_test.py, tests/util_test.py
- Fix type of `expires_in` data element returned by `/auth/openid/token`
- Fix encoding of JWKS
=> [DM-26682] Fix OpenID Connect bugs

.pre-commit-config.yaml, pyproject.toml, requirements/dev.in, requirements/dev.txt, src/gafaelfawr/templates/new_token.html, src/gafaelfawr/templates/tokens.html, tests/conftest.py, tests/pages/base.py, tests/pages/tokens.py, tests/selenium/tokens_test.py, tests/setup.py, tests/support/selenium.py
- Add support for Selenium tests and an initial test for the token creation flow
- Update pre-commit configuration
- Some code cleanup
=> [DM-26751] Add Selenium tests

.pre-commit-config.yaml, tests/services/token_test.py
- Update dependencies
- Fix intermittent test failure with token expiration tests
=> [DM-24818]

docs/_static/architecture.py, docs/applications.rst, docs/arch/overview.rst, docs/configuration.rst, docs/install.rst, requirements/main.in, requirements/main.txt, src/gafaelfawr/cli.py, src/gafaelfawr/config.py, src/gafaelfawr/constants.py, src/gafaelfawr/dependencies/auth.py, src/gafaelfawr/dependencies/logger.py, src/gafaelfawr/exceptions.py, src/gafaelfawr/factory.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/token.py, src/gafaelfawr/services/kubernetes.py, src/gafaelfawr/services/token.py, src/gafaelfawr/storage/kubernetes.py, tests/cli_test.py, tests/conftest.py, tests/handlers/api_history_test.py, tests/services/kubernetes_test.py, tests/services/token_test.py, tests/settings/github.yaml.in, tests/support/kubernetes.py, tests/support/selenium.py, tests/support/setup.py, ui/package-lock.json
- Add a framework for command-line invocation of background tasks
- Add support for maintaining Kubernetes secrets containing service tokens
=> [DM-28898] Add Kubernetes secret management support

docs/install.rst
The Helm chart was significantly reworked to follow best practices,
which included renaming a lot of parameters.  Update the docs to
match.
=> [DM-29085] Update Helm chart documentation for refactor

docs/configuration.rst, src/gafaelfawr/config.py, tests/settings_test.py, tests/support/settings.py, ui/package-lock.json
- Allow the database password to be separately set via an environment variable
- Update JavaScript pins
=> [DM-28120] Support separate database_password setting

tests/handlers/login_github_test.py
Confirm that we set the attributes we expect on the state cookie.
=> [DM-29924] Test state cookie attributes

CHANGELOG.rst, README.rst, docs/index.rst
Thanks, Chris Samuel.  Closes #226
=> Improve pronunciation guide

CHANGELOG.rst, src/gafaelfawr/cli.py, src/gafaelfawr/factory.py
We had one problem where Gafaelfawr wouldn't start because it
couldn't reach PostgreSQL.  Add some startup logging to make it
easier to discover that problem in the future.
=> [DM-29365] Add more debug logging of startup

.pre-commit-config.yaml, CHANGELOG.rst, Dockerfile, scripts/prestart.sh, src/gafaelfawr/database.py, tests/conftest.py, tests/pages/tokens.py, tests/selenium/tokens_test.py, tests/support/selenium.py, ui/src/components/tokenChangeSearch.js, ui/src/components/tokenChangeTable.js, ui/src/components/tokenData.js
- Display token key and type in the token change history display
- Initialize the database as part of container startup
- Add additional startup logging at the DEBUG level
- Improve error reporting if the database connection fails
=> [DM-30369] Fix some bugs uncovered by the recent deployment

CHANGELOG.rst, Makefile, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/storage/kubernetes.py
The wrong syntax was used for kicking off the Kubernetes watcher.
=> [DM-33121] Fix Kubernetes watcher invocation

Makefile
pip-tools has fixed its incompatibility with pip 22.
=> [DM-33662] Unpin pip

.github/workflows/ci.yaml, docs/applications.rst, src/gafaelfawr/schema/base.py
- Update Chronograf OpenID Connect documentation with another setting
- Update how `declarative_base` is imported from SQLAlchemy
- Update the caching method for Docker image builds
=> [DM-33662] Minor Gafaelfawr fixes

CHANGELOG.rst, docs/arch/configuration.rst, docs/arch/security.rst, examples/docker/gafaelfawr.yaml, examples/gafaelfawr-dev.yaml, examples/gafaelfawr-github.yaml, examples/gafaelfawr-oidc.yaml, examples/secrets/bootstrap-token, requirements/dev.txt, src/gafaelfawr/config.py, tests/settings/bad-token.yaml.in, tests/settings/github-oidc-server.yaml.in, tests/settings/github.yaml.in, tests/settings_test.py, tests/support/settings.py, ui/package-lock.json
We were using environment variables for some secrets and files
for other settings.  Standardize on files for all secrets and add
some background to the architecture documentation.
=> [DM-34334] Standardize on using files to pass in secrets

src/gafaelfawr/storage/ldap.py
This change fixes three issues with error handling in LDAP
connections:
* Timed-out connections were being reopened outside of the
AIOPoolContextManager, which means that we were reopening a
connection that was already returned to the pool.  That in turn
meant potentially racing another thread of execution that got
the connection out of the pool and thought it was valid.  Fix
this by catching exceptions inside the context manager and
reopening the connection while it's still "ours."
* If reopening the connection after timout failed, we threw an
uncaught bonsai exception because there was no surrounding
try/except block.  The generic LDAPError except block was
parallel with the timeout block, and instead should have wrapped
the entire operation and caught the exception after it was thrown …
=> [DM-35765] Better LDAP connection error handling

CHANGELOG.md
Use traditional wrapping rather than one line per sentence, since
these entries are intended for cutting and pasting into GitHub
release notes, and those preserve newlines.
=> [DM-35644] Rewrap CHANGELOG.md

.pre-commit-config.yaml, pyproject.toml, src/gafaelfawr/cli.py, src/gafaelfawr/handlers/oidc.py, src/gafaelfawr/models/admin.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/models/token.py, src/gafaelfawr/schema/admin.py, src/gafaelfawr/schema/admin_history.py, src/gafaelfawr/schema/subtoken.py, src/gafaelfawr/schema/token.py, src/gafaelfawr/schema/token_auth_history.py, src/gafaelfawr/schema/token_change_history.py
Add a linter to run pydocstyle and fix the errors that it uncovered.
=> [DM-35644] Add pydocstyle linting

src/gafaelfawr/main.py, src/gafaelfawr/slack.py, tests/settings/github.yaml.in, tests/settings/oidc.yaml.in, tests/slack_test.py
- Fix syntax of Slack exception reports
- Unconditionally inject the route handler for exception reporting
- Log initialization of the Slack webhook
=> [DM-35872] Fix Slack alerting

CHANGELOG.md, requirements/dev.txt, requirements/main.txt, src/gafaelfawr/cli.py, src/gafaelfawr/factory.py, src/gafaelfawr/services/token.py, src/gafaelfawr/slack.py, src/gafaelfawr/storage/base.py, src/gafaelfawr/storage/token.py, tests/cli_test.py, tests/conftest.py, tests/services/token_test.py, ui/package-lock.json
Add a command that does a consistency audit of the Gafaelfawr
data stores and reports any problems to Slack.  This contains a
selection of simple and obvious checks, and we can add more checks
later based on problems we've seen in practice.
=> [DM-35959] Add periodic audit command

.github/workflows/ci.yaml, CHANGELOG.md, ui/package-lock.json
- Re-enable link checking
- Update JavaScript dependencies
- Complete change log for 6.1.0
=> DM-36447: Prepare 6.1.0 release

CHANGELOG.md, src/gafaelfawr/config.py, src/gafaelfawr/factory.py, src/gafaelfawr/keypair.py, src/gafaelfawr/middleware/state.py, src/gafaelfawr/models/history.py, src/gafaelfawr/models/kubernetes.py, src/gafaelfawr/models/link.py, src/gafaelfawr/models/oidc.py, src/gafaelfawr/models/state.py, src/gafaelfawr/models/token.py
- Add missing change log entry for diagnosing multiple usernames
- Use the Self type for classmethod constructors
=> DM-38170: Update changelog, use Self type

CHANGELOG.md, docs/user-guide/helm.rst
Document the quota configuration and semantics.
=> DM-37833: Add documentation for rudimentary quota support

.github/workflows/dependencies.yaml
Rely on neophile's new ability to automatically determine an appropriate email address.
=> DM-39919: Stop setting neophile email

.github/workflows/ci.yaml
Use the new lsst-sqre/build-and-push-to-ghcr GitHub Action.
=> DM-39989: Use new GitHub Action for Docker image

src/gafaelfawr/storage/ldap.py
Looking up group names and groups with GIDs largely repeated the same code. Refactor that code into more internal methods to avoid duplication.
=> DM-23878: Refactor LDAP code to avoid duplication

requirements/dev.txt, requirements/main.txt
Picks up a security fix for gitpython.
=> DM-42384: Update Python dependencies

tests/conftest.py, ui/src/components/tokenChangeSearchForm.js, ui/src/components/tokenList.js
Add a section for OpenID Connect tokens to the UI, and add oidc tokens as a type that can be searched for in the token history.
=> DM-42384: Add OpenID Connect tokens to the UI

src/gafaelfawr/operator/health.py
The Kopf health check was calling the wrong method. Fix that, and also fix the typing so that we get proper type checking.
=> DM-43288: Fix Kopf health check

src/gafaelfawr/main.py
The FastAPI bug with serialization of certain types of validation errors has been fixed, so the workaround can be dropped.
=> DM-44269: Remove workaround for FastAPI bug

src/gafaelfawr/storage/kubernetes.py
When wrapping Kubernetes storage class methods to convert exceptions, use the new ParamSpec support to avoid destroying type information.
=> DM-44490: Use ParamSpec for Kubernetes exception wrapper

ruff-shared.toml, src/gafaelfawr/handlers/auth.py
Update to the current version of the shared Ruff configuration. This relaxes the increase to the McCabe complexity constraint, which required refactoring another bit of code to move a complex check into a function.
=> DM-45779: Update shared Ruff configuration

CHANGELOG.md, changelog.d/20240528_150942_rra_DM_44567.md, changelog.d/20240814_105528_rra_DM_45518.md, changelog.d/20240814_133538_rra_DM_45779.md, changelog.d/20240814_154819_rra_DM_45779.md, changelog.d/20240820_162506_rra_DM_45858.md, changelog.d/20240821_140900_rra_DM_45858.md, changelog.d/20240911_155549_rra_DM_46034a.md, changelog.d/20240919_154251_rra_DM_46399.md, changelog.d/20240919_172648_rra_DM_46399.md, changelog.d/20240920_170722_rra_DM_46399.md, changelog.d/20240925_110256_rra_DM_46399.md, changelog.d/20240925_144604_rra_DM_46399.md
Collect the change log for the 12.0.0 release.
=> DM-46821: Prepare 12.0.0 release

CHANGELOG.md, changelog.d/20241021_092723_rra_DM_47011.md
Collect the change log for the 12.0.1 release.
=> DM-47011: Prepare 12.0.1 release

CHANGELOG.md, changelog.d/20241021_153026_rra_DM_47011.md, changelog.d/20241025_160624_rra_DM_47148.md, changelog.d/20241028_133552_rra_DM_47148.md, changelog.d/20241028_150742_rra_DM_47148.md
Collect the change log for the Gafaelfawr 12.1.0 release.
=> DM-47148: Prepare 12.1.0 release

CHANGELOG.md, changelog.d/20241118_171429_rra_DM_47646.md, changelog.d/20241119_153825_rra_DM_47646.md
Collect the change log for the 12.1.1 release.
=> DM-47646: Prepare Gafaelfawr 12.1.1

src/gafaelfawr/exceptions.py, src/gafaelfawr/storage/firestore.py
When Google Firestore API calls fail, catch the Google API exception and wrap it in a custom exception so that Gafaelfawr can add context and report a nicer exception to Slack.
=> Capture more information in Firestore exceptions

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250226_150901_rra_DM_49149.md, changelog.d/20250226_170821_rra_DM_49149.md, changelog.d/20250226_180120_rra_DM_49149.md, changelog.d/20250303_152128_rra_DM_49149.md, changelog.d/20250303_180647_rra_DM_49149.md, changelog.d/20250304_151908_rra_DM_49149.md, changelog.d/20250304_184003_rra_DM_49315.md, changelog.d/20250305_154010_rra_DM_49315.md, changelog.d/20250305_171727_rra_DM_49315.md, changelog.d/20250306_123621_rra_DM_49347.md, changelog.d/20250314_144218_rra_DM_49493.md
Collect the change log for the 13.0.0 release and update the uv version in GitHub Actions and `Dockerfile`.
=> DM-49493: Prepare 13.0.0 release

docs/user-guide/cors.rst, docs/user-guide/helm.rst
Update several inks that are returning permanent redirects to other pages.
=> Fix permanent redirects

CHANGELOG.md, changelog.d/20250701_170347_rra_DM_51679.md, changelog.d/20250714_154548_rra_rate_limit.md, changelog.d/20250715_153805_rra_DM_51818.md, changelog.d/20250716_171549_rra_DM_51818.md, changelog.d/20250718_090750_rra_DM_51859.md, changelog.d/20250721_161306_rra_DM_51892.md, changelog.d/20250721_172249_rra_DM_51818.md, ui/package-lock.json, uv.lock
Collect change log for the 14.0.0 release. Update Python and JavaScript dependencies.
=> DM-51818: Prepare 14.0.0 release
